### ISSUE TITLE
StripeController#events (NoMethodError) "undefined method `subscription_id=' for "cus_B4uAYUHo3l0iYu":String"

### ISSUE THREAD

**Issue by tannakartikey** [tannakartikey/currents#24]
<table><tr><th>Exception</th><td>undefined method `subscription_id=&#39; for &quot;cus_B4uAYUHo3l0iYu&quot;:String</td></tr><tr><th>Last Occurrence</th><td>July 23, 2017 14:50:48 +0000</td></tr><tr><th>Count</th><td>1</td></tr></table>

## Stack Trace
<pre><a href='https://github.com/tannakartikey/currents/blob/1f246b06fe6fceba481a30d2e3c4f7b9cd05921a/app/controllers/stripe_controller.rb#L23'>[app].../app/controllers/stripe_controller.rb:23:in `events'</a>
[bundle].../gems/actionpack-4.2.7.1/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
[bundle].../gems/actionpack-4.2.7.1/lib/abstract_controller/base.rb:198:in `process_action'
[bundle].../gems/actionpack-4.2.7.1/lib/action_controller/metal/rendering.rb:10:in `process_action'
[bundle].../gems/actionpack-4.2.7.1/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:117:in `call'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:505:in `call'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
[bundle].../gems/actionpack-4.2.7.1/lib/abstract_controller/callbacks.rb:19:in `process_action'
[bundle].../gems/actionpack-4.2.7.1/lib/action_controller/metal/rescue.rb:29:in `process_action'
[bundle].../gems/actionpack-4.2.7.1/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `block in instrument'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `instrument'
[bundle].../gems/actionpack-4.2.7.1/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
[bundle].../gems/actionpack-4.2.7.1/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
[bundle].../gems/activerecord-4.2.7.1/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
[bundle].../gems/actionpack-4.2.7.1/lib/abstract_controller/base.rb:137:in `process'
[bundle].../gems/actionview-4.2.7.1/lib/action_view/rendering.rb:30:in `process'
[bundle].../gems/actionpack-4.2.7.1/lib/action_controller/metal.rb:196:in `dispatch'
[bundle].../gems/actionpack-4.2.7.1/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
[bundle].../gems/actionpack-4.2.7.1/lib/action_controller/metal.rb:237:in `block in action'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/routing/route_set.rb:43:in `serve'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/journey/router.rb:43:in `block in serve'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/journey/router.rb:30:in `each'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/journey/router.rb:30:in `serve'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/routing/route_set.rb:817:in `call'
[bundle].../gems/party_foul-1.5.5/lib/party_foul/middleware.rb:8:in `call'
[bundle].../gems/warden-1.2.7/lib/warden/manager.rb:36:in `block in call'
[bundle].../gems/warden-1.2.7/lib/warden/manager.rb:35:in `catch'
[bundle].../gems/warden-1.2.7/lib/warden/manager.rb:35:in `call'
[bundle].../gems/rack-1.6.8/lib/rack/etag.rb:24:in `call'
[bundle].../gems/rack-1.6.8/lib/rack/conditionalget.rb:38:in `call'
[bundle].../gems/rack-1.6.8/lib/rack/head.rb:13:in `call'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/flash.rb:260:in `call'
[bundle].../gems/rack-1.6.8/lib/rack/session/abstract/id.rb:225:in `context'
[bundle].../gems/rack-1.6.8/lib/rack/session/abstract/id.rb:220:in `call'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/cookies.rb:560:in `call'
[bundle].../gems/activerecord-4.2.7.1/lib/active_record/query_cache.rb:36:in `call'
[bundle].../gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
[bundle].../gems/railties-4.2.7.1/lib/rails/rack/logger.rb:38:in `call_app'
[bundle].../gems/railties-4.2.7.1/lib/rails/rack/logger.rb:20:in `block in call'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:68:in `block in tagged'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:26:in `tagged'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:68:in `tagged'
[bundle].../gems/railties-4.2.7.1/lib/rails/rack/logger.rb:20:in `call'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/request_id.rb:21:in `call'
[bundle].../gems/rack-1.6.8/lib/rack/methodoverride.rb:22:in `call'
[bundle].../gems/rack-1.6.8/lib/rack/runtime.rb:18:in `call'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/static.rb:120:in `call'
[bundle].../gems/rack-1.6.8/lib/rack/sendfile.rb:113:in `call'
[bundle].../gems/railties-4.2.7.1/lib/rails/engine.rb:518:in `call'
[bundle].../gems/railties-4.2.7.1/lib/rails/application.rb:165:in `call'
[bundle].../gems/rack-1.6.8/lib/rack/content_length.rb:15:in `call'
[bundle].../gems/puma-3.9.1/lib/puma/configuration.rb:224:in `call'
[bundle].../gems/puma-3.9.1/lib/puma/server.rb:602:in `handle_request'
[bundle].../gems/puma-3.9.1/lib/puma/server.rb:435:in `process_client'
[bundle].../gems/puma-3.9.1/lib/puma/server.rb:299:in `block in run'
[bundle].../gems/puma-3.9.1/lib/puma/thread_pool.rb:120:in `block in spawn_thread'</pre>
Fingerprint: `e1aa373a6c7268f7ab20062082c07d6afd9efc98`

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>July 23, 2017 14:50:48 +0000</td></tr><tr><th>URL</th><td>[POST] /stripe_events</td></tr><tr><th>Params</th><td><table><tr><th>id</th><td>evt_1AilPALl1LzrhllYJjn1YHzB</td></tr><tr><th>object</th><td>event</td></tr><tr><th>api_version</th><td>2017-06-05</td></tr><tr><th>created</th><td>1500821400</td></tr><tr><th>data</th><td><table><tr><th>object</th><td><table><tr><th>id</th><td>sub_B4uAQNcE5Eldc6</td></tr><tr><th>object</th><td>subscription</td></tr><tr><th>application_fee_percent</th><td></td></tr><tr><th>cancel_at_period_end</th><td>false</td></tr><tr><th>canceled_at</th><td>1500821400</td></tr><tr><th>created</th><td>1500817397</td></tr><tr><th>current_period_end</th><td>1503496097</td></tr><tr><th>current_period_start</th><td>1500817697</td></tr><tr><th>customer</th><td>cus_B4uAYUHo3l0iYu</td></tr><tr><th>discount</th><td></td></tr><tr><th>ended_at</th><td>1500821400</td></tr><tr><th>items</th><td><table><tr><th>object</th><td>list</td></tr><tr><th>data</th><td>[{&quot;id&quot;=&gt;&quot;si_1AikMbLl1LzrhllYAhrW46v4&quot;, &quot;object&quot;=&gt;&quot;subscription_item&quot;, &quot;created&quot;=&gt;1500817398, &quot;metadata&quot;=&gt;{}, &quot;plan&quot;=&gt;{&quot;id&quot;=&gt;&quot;monthly&quot;, &quot;object&quot;=&gt;&quot;plan&quot;, &quot;amount&quot;=&gt;900, &quot;created&quot;=&gt;1500126335, &quot;currency&quot;=&gt;&quot;usd&quot;, &quot;interval&quot;=&gt;&quot;month&quot;, &quot;interval_count&quot;=&gt;1, &quot;livemode&quot;=&gt;false, &quot;metadata&quot;=&gt;{}, &quot;name&quot;=&gt;&quot;Monthly&quot;, &quot;statement_descriptor&quot;=&gt;nil, &quot;trial_period_days&quot;=&gt;nil}, &quot;quantity&quot;=&gt;1}]</td></tr><tr><th>has_more</th><td>false</td></tr><tr><th>total_count</th><td>1</td></tr><tr><th>url</th><td>/v1/subscription_items?subscription=sub_B4uAQNcE5Eldc6</td></tr></table></td></tr><tr><th>livemode</th><td>false</td></tr><tr><th>metadata</th><td><table></table></td></tr><tr><th>plan</th><td><table><tr><th>id</th><td>monthly</td></tr><tr><th>object</th><td>plan</td></tr><tr><th>amount</th><td>900</td></tr><tr><th>created</th><td>1500126335</td></tr><tr><th>currency</th><td>usd</td></tr><tr><th>interval</th><td>month</td></tr><tr><th>interval_count</th><td>1</td></tr><tr><th>livemode</th><td>false</td></tr><tr><th>metadata</th><td><table></table></td></tr><tr><th>name</th><td>Monthly</td></tr><tr><th>statement_descriptor</th><td></td></tr><tr><th>trial_period_days</th><td></td></tr></table></td></tr><tr><th>quantity</th><td>1</td></tr><tr><th>start</th><td>1500817397</td></tr><tr><th>status</th><td>canceled</td></tr><tr><th>tax_percent</th><td></td></tr><tr><th>trial_end</th><td>1500817697</td></tr><tr><th>trial_start</th><td>1500817397</td></tr></table></td></tr></table></td></tr><tr><th>livemode</th><td>false</td></tr><tr><th>pending_webhooks</th><td>1</td></tr><tr><th>request</th><td><table><tr><th>id</th><td></td></tr><tr><th>idempotency_key</th><td></td></tr></table></td></tr><tr><th>type</th><td>customer.subscription.deleted</td></tr><tr><th>controller</th><td>stripe</td></tr><tr><th>action</th><td>events</td></tr><tr><th>stripe</th><td><table><tr><th>id</th><td>evt_1AilPALl1LzrhllYJjn1YHzB</td></tr><tr><th>object</th><td>event</td></tr><tr><th>api_version</th><td>2017-06-05</td></tr><tr><th>created</th><td>1500821400</td></tr><tr><th>data</th><td><table><tr><th>object</th><td><table><tr><th>id</th><td>sub_B4uAQNcE5Eldc6</td></tr><tr><th>object</th><td>subscription</td></tr><tr><th>application_fee_percent</th><td></td></tr><tr><th>cancel_at_period_end</th><td>false</td></tr><tr><th>canceled_at</th><td>1500821400</td></tr><tr><th>created</th><td>1500817397</td></tr><tr><th>current_period_end</th><td>1503496097</td></tr><tr><th>current_period_start</th><td>1500817697</td></tr><tr><th>customer</th><td>cus_B4uAYUHo3l0iYu</td></tr><tr><th>discount</th><td></td></tr><tr><th>ended_at</th><td>1500821400</td></tr><tr><th>items</th><td><table><tr><th>object</th><td>list</td></tr><tr><th>data</th><td>[{&quot;id&quot;=&gt;&quot;si_1AikMbLl1LzrhllYAhrW46v4&quot;, &quot;object&quot;=&gt;&quot;subscription_item&quot;, &quot;created&quot;=&gt;1500817398, &quot;metadata&quot;=&gt;{}, &quot;plan&quot;=&gt;{&quot;id&quot;=&gt;&quot;monthly&quot;, &quot;object&quot;=&gt;&quot;plan&quot;, &quot;amount&quot;=&gt;900, &quot;created&quot;=&gt;1500126335, &quot;currency&quot;=&gt;&quot;usd&quot;, &quot;interval&quot;=&gt;&quot;month&quot;, &quot;interval_count&quot;=&gt;1, &quot;livemode&quot;=&gt;false, &quot;metadata&quot;=&gt;{}, &quot;name&quot;=&gt;&quot;Monthly&quot;, &quot;statement_descriptor&quot;=&gt;nil, &quot;trial_period_days&quot;=&gt;nil}, &quot;quantity&quot;=&gt;1}]</td></tr><tr><th>has_more</th><td>false</td></tr><tr><th>total_count</th><td>1</td></tr><tr><th>url</th><td>/v1/subscription_items?subscription=sub_B4uAQNcE5Eldc6</td></tr></table></td></tr><tr><th>livemode</th><td>false</td></tr><tr><th>metadata</th><td><table></table></td></tr><tr><th>plan</th><td><table><tr><th>id</th><td>monthly</td></tr><tr><th>object</th><td>plan</td></tr><tr><th>amount</th><td>900</td></tr><tr><th>created</th><td>1500126335</td></tr><tr><th>currency</th><td>usd</td></tr><tr><th>interval</th><td>month</td></tr><tr><th>interval_count</th><td>1</td></tr><tr><th>livemode</th><td>false</td></tr><tr><th>metadata</th><td><table></table></td></tr><tr><th>name</th><td>Monthly</td></tr><tr><th>statement_descriptor</th><td></td></tr><tr><th>trial_period_days</th><td></td></tr></table></td></tr><tr><th>quantity</th><td>1</td></tr><tr><th>start</th><td>1500817397</td></tr><tr><th>status</th><td>canceled</td></tr><tr><th>tax_percent</th><td></td></tr><tr><th>trial_end</th><td>1500817697</td></tr><tr><th>trial_start</th><td>1500817397</td></tr></table></td></tr></table></td></tr><tr><th>livemode</th><td>false</td></tr><tr><th>pending_webhooks</th><td>1</td></tr><tr><th>request</th><td><table><tr><th>id</th><td></td></tr><tr><th>idempotency_key</th><td></td></tr></table></td></tr><tr><th>type</th><td>customer.subscription.deleted</td></tr></table></td></tr></table></td></tr><tr><th>Session</th><td><table></table></td></tr><tr><th>IP Address</th><td>&lt;a href=&#39;http://ipinfo.io/54.187.205.235&#39;&gt;54.187.205.235&lt;/a&gt;</td></tr><tr><th>HTTP Headers</th><td><table><tr><th>Version</th><td>HTTP/1.1</td></tr><tr><th>User Agent</th><td>Stripe/1.0 (+https://stripe.com/docs/webhooks)</td></tr><tr><th>Accept Encoding</th><td>gzip, deflate</td></tr><tr><th>Accept</th><td>*/*; q=0.5, application/xml</td></tr></table></td></tr></table>
