### ISSUE TITLE
#<StripeController:0xXXXXXX>#events (NoMethodError) "undefined method `previous_attributes' for #<Stripe::Event:0xXXXXXX>"

### ISSUE THREAD

**Issue by tannakartikey** [tannakartikey/currents#266]
<table><tr><th>Exception</th><td>undefined method `previous_attributes&#39; for #&lt;Stripe::Event:0x007fd56572cbe8&gt;</td></tr><tr><th>Last Occurrence</th><td>June 11, 2018 14:39:34 +0000</td></tr><tr><th>Count</th><td>257</td></tr></table>

## Stack Trace
<pre>[bundle].../gems/stripe-3.3.1/lib/stripe/stripe_object.rb:285:in `method_missing'
<a href='https://github.com/tannakartikey/currents/blob/fea797af242ab83bdcba775e643b0f6d54ba6a16/app/controllers/stripe_controller.rb#L64'>[app].../app/controllers/stripe_controller.rb:64:in `event_process'</a>
<a href='https://github.com/tannakartikey/currents/blob/fea797af242ab83bdcba775e643b0f6d54ba6a16/app/controllers/stripe_controller.rb#L20'>[app].../app/controllers/stripe_controller.rb:20:in `block in events'</a></pre>
Fingerprint: `1538baee2e5d40825d3c9f0c7d3789cdfb32c169`

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2017 14:11:33 +0000</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2017 14:12:33 +0000</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2017 14:14:47 +0000</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2017 14:15:03 +0000</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2017 14:16:09 +0000</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2017 14:16:34 +0000</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2017 14:17:17 +0000</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2017 14:17:42 +0000</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2017 14:18:12 +0000</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2017 14:18:35 +0000</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2017 14:19:03 +0000</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2017 14:19:47 +0000</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2017 14:22:30 +0000</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2017 14:23:16 +0000</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2017 14:23:23 +0000</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2017 14:24:02 +0000</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2017 14:25:02 +0000</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2017 14:25:17 +0000</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2017 14:25:42 +0000</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2017 14:27:23 +0000</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2017 14:28:51 +0000</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2017 14:29:26 +0000</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2017 14:29:37 +0000</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2017 14:30:14 +0000</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2017 14:31:14 +0000</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2017 14:31:28 +0000</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2017 14:32:04 +0000</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2017 14:33:40 +0000</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2017 14:35:12 +0000</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2017 14:36:32 +0000</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2017 14:36:54 +0000</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2017 14:37:03 +0000</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2017 14:38:29 +0000</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2017 14:38:54 +0000</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2017 14:39:02 +0000</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2017 14:39:25 +0000</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2017 14:39:38 +0000</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2017 14:40:04 +0000</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2017 14:42:13 +0000</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2017 14:42:13 +0000</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2017 14:43:07 +0000</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2017 14:43:34 +0000</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2017 14:43:49 +0000</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2017 14:45:25 +0000</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2017 14:47:07 +0000</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2017 14:48:07 +0000</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2017 14:50:27 +0000</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2017 14:51:34 +0000</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2017 14:51:36 +0000</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2017 14:52:53 +0000</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2017 14:52:57 +0000</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2017 14:56:46 +0000</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2017 14:57:36 +0000</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2017 14:58:06 +0000</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2017 14:59:50 +0000</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2017 15:00:29 +0000</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2017 15:01:27 +0000</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2017 15:02:26 +0000</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2017 15:03:47 +0000</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2017 15:04:22 +0000</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2017 15:09:44 +0000</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2017 15:11:09 +0000</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2017 15:11:19 +0000</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2017 15:15:03 +0000</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2017 15:17:02 +0000</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2017 15:17:39 +0000</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2017 15:20:33 +0000</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2017 15:24:08 +0000</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2017 15:28:17 +0000</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2017 15:41:49 +0000</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 30, 2017 12:58:09 +0530</td></tr><tr><th>Params</th><td>#&lt;User:0x007f76fbac3ba8&gt;</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 30, 2017 20:51:38 +0530</td></tr><tr><th>Params</th><td>#&lt;User:0x007f76e4e5c1a0&gt;</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 30, 2017 20:51:41 +0530</td></tr><tr><th>Params</th><td>#&lt;User:0x007f76e4b21b20&gt;</td></tr></table>
