### ISSUE TITLE
#<StripeController:0xXXXXXX>#events (NoMethodError) "undefined method `is_active=' for nil:NilClass"

### ISSUE THREAD

**Issue by tannakartikey** [tannakartikey/currents#267]
<table><tr><th>Exception</th><td>undefined method `is_active=&#39; for nil:NilClass</td></tr><tr><th>Last Occurrence</th><td>May 03, 2018 02:56:46 +0000</td></tr><tr><th>Count</th><td>29</td></tr></table>

## Stack Trace
<pre><a href='https://github.com/tannakartikey/currents/blob/fea797af242ab83bdcba775e643b0f6d54ba6a16/app/controllers/stripe_controller.rb#L76'>[app].../app/controllers/stripe_controller.rb:76:in `event_process'</a>
<a href='https://github.com/tannakartikey/currents/blob/fea797af242ab83bdcba775e643b0f6d54ba6a16/app/controllers/stripe_controller.rb#L20'>[app].../app/controllers/stripe_controller.rb:20:in `block in events'</a></pre>
Fingerprint: `d1c97c6d741df1d811500b08ea2322601091f661`

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2017 14:36:11 +0000</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2017 14:39:05 +0000</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>November 28, 2017 14:26:15 +0000</td></tr><tr><th>Params</th><td>nil</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>November 28, 2017 14:26:15 +0000</td></tr><tr><th>Params</th><td>nil</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>December 18, 2017 22:11:31 +0000</td></tr><tr><th>Params</th><td>nil</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>December 18, 2017 22:15:50 +0000</td></tr><tr><th>Params</th><td>nil</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>December 18, 2017 22:16:35 +0000</td></tr><tr><th>Params</th><td>nil</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>December 18, 2017 23:37:34 +0000</td></tr><tr><th>Params</th><td>nil</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>January 23, 2018 21:15:50 +0000</td></tr><tr><th>Params</th><td>nil</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>January 23, 2018 21:27:47 +0000</td></tr><tr><th>Params</th><td>nil</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 20, 2018 02:13:45 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>invoice.payment_succeeded</td></tr><tr><th>event_id</th><td>evt_1CIokjDyDCrOMJ6PbHjjYOV5</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 20, 2018 02:15:45 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>invoice.payment_succeeded</td></tr><tr><th>event_id</th><td>evt_1CIomnDyDCrOMJ6PFSRJnSz7</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 20, 2018 02:19:40 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>invoice.payment_succeeded</td></tr><tr><th>event_id</th><td>evt_1CIoqbDyDCrOMJ6P12z2iUM6</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 20, 2018 02:20:29 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>invoice.payment_succeeded</td></tr><tr><th>event_id</th><td>evt_1CIorMDyDCrOMJ6P3ObcGgpw</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 20, 2018 02:22:04 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>invoice.payment_succeeded</td></tr><tr><th>event_id</th><td>evt_1CIoswDyDCrOMJ6PWnwXVi1O</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 20, 2018 02:23:39 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>invoice.payment_succeeded</td></tr><tr><th>event_id</th><td>evt_1CIouUDyDCrOMJ6Psx8A7nQb</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 20, 2018 02:25:04 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>invoice.payment_succeeded</td></tr><tr><th>event_id</th><td>evt_1CIovnDyDCrOMJ6P6JH67ADQ</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 20, 2018 02:26:05 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>invoice.payment_succeeded</td></tr><tr><th>event_id</th><td>evt_1CIowlDyDCrOMJ6PhyIvcNDW</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 20, 2018 17:17:54 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>invoice.payment_succeeded</td></tr><tr><th>event_id</th><td>evt_1CJ2roDyDCrOMJ6PxAJpwfhD</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 23, 2018 19:15:46 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>invoice.payment_succeeded</td></tr><tr><th>event_id</th><td>evt_1CKA7qDyDCrOMJ6PcNYdHS91</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 23, 2018 19:20:00 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>invoice.payment_succeeded</td></tr><tr><th>event_id</th><td>evt_1CKACdDyDCrOMJ6PpbmJcfGw</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 23, 2018 19:26:18 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>invoice.payment_succeeded</td></tr><tr><th>event_id</th><td>evt_1CKAIhDyDCrOMJ6PUCPw3wTW</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 23, 2018 19:29:43 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>invoice.payment_succeeded</td></tr><tr><th>event_id</th><td>evt_1CKAM5DyDCrOMJ6PAST4n9gE</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 23, 2018 19:31:14 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>invoice.payment_succeeded</td></tr><tr><th>event_id</th><td>evt_1CKANXDyDCrOMJ6Pt2A85Eji</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 23, 2018 19:47:40 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>invoice.payment_succeeded</td></tr><tr><th>event_id</th><td>evt_1CKA7qDyDCrOMJ6PcNYdHS91</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 23, 2018 19:56:59 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>invoice.payment_succeeded</td></tr><tr><th>event_id</th><td>evt_1CKAmUDyDCrOMJ6PuK2eNInr</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 24, 2018 01:12:19 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>invoice.payment_succeeded</td></tr><tr><th>event_id</th><td>evt_1CKFhTDyDCrOMJ6Po5m1jULr</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 24, 2018 01:22:06 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>invoice.payment_succeeded</td></tr><tr><th>event_id</th><td>evt_1CKFr5DyDCrOMJ6Pgtdibgh9</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>May 03, 2018 02:56:46 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>invoice.payment_succeeded</td></tr><tr><th>event_id</th><td>evt_1CNXcGDyDCrOMJ6PUCBdbGm1</td></tr></table></td></tr></table>
