### ISSUE TITLE
#<StripeController:0xXXXXXX>#events (NoMethodError) "undefined method `payment_source' for nil:NilClass"

### ISSUE THREAD

**Issue by tannakartikey** [tannakartikey/currents#268]
<table><tr><th>Exception</th><td>undefined method `payment_source&#39; for nil:NilClass</td></tr><tr><th>Last Occurrence</th><td>May 10, 2018 00:02:42 +0000</td></tr><tr><th>Count</th><td>16</td></tr></table>

## Stack Trace
<pre><a href='https://github.com/tannakartikey/currents/blob/fea797af242ab83bdcba775e643b0f6d54ba6a16/app/controllers/stripe_controller.rb#L48'>[app].../app/controllers/stripe_controller.rb:48:in `event_process'</a>
<a href='https://github.com/tannakartikey/currents/blob/fea797af242ab83bdcba775e643b0f6d54ba6a16/app/controllers/stripe_controller.rb#L20'>[app].../app/controllers/stripe_controller.rb:20:in `block in events'</a></pre>
Fingerprint: `e07808668ebaf1d923decf2b07379517f6ede989`

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 28, 2017 14:41:29 +0000</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>November 28, 2017 14:32:16 +0000</td></tr><tr><th>Params</th><td>nil</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>November 28, 2017 14:32:17 +0000</td></tr><tr><th>Params</th><td>nil</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>December 18, 2017 22:21:34 +0000</td></tr><tr><th>Params</th><td>nil</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>December 18, 2017 22:23:55 +0000</td></tr><tr><th>Params</th><td>nil</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>January 23, 2018 21:21:55 +0000</td></tr><tr><th>Params</th><td>nil</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>January 23, 2018 21:32:19 +0000</td></tr><tr><th>Params</th><td>nil</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>January 26, 2018 21:12:16 +0000</td></tr><tr><th>Params</th><td>nil</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 20, 2018 02:33:01 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>customer.subscription.updated</td></tr><tr><th>event_id</th><td>evt_1CIp3UDyDCrOMJ6PDlkYs8uJ</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 20, 2018 17:23:24 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>customer.subscription.updated</td></tr><tr><th>event_id</th><td>evt_1CJ2x8DyDCrOMJ6PSDc36DIL</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 23, 2018 19:38:24 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>customer.subscription.updated</td></tr><tr><th>event_id</th><td>evt_1CKAUUDyDCrOMJ6Pe0MppBbz</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 23, 2018 20:02:41 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>customer.subscription.updated</td></tr><tr><th>event_id</th><td>evt_1CKArxDyDCrOMJ6PXkCoYJDB</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 24, 2018 01:19:14 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>customer.subscription.updated</td></tr><tr><th>event_id</th><td>evt_1CKFoKDyDCrOMJ6P73L8tFaE</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 24, 2018 01:27:40 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>customer.subscription.updated</td></tr><tr><th>event_id</th><td>evt_1CKFwMDyDCrOMJ6Pev5NZqBN</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>May 03, 2018 03:02:50 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>customer.subscription.updated</td></tr><tr><th>event_id</th><td>evt_1CNXiVDyDCrOMJ6P7ptfQ4gY</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>May 10, 2018 00:02:42 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>customer.subscription.updated</td></tr><tr><th>event_id</th><td>evt_1CQ2DkDyDCrOMJ6PJVZYKJQB</td></tr></table></td></tr></table>
