### ISSUE TITLE
# (NoMethodError) "undefined method `delete' for nil:NilClass"

### ISSUE THREAD

**Issue by tannakartikey** [tannakartikey/currents#270]
<table><tr><th>Exception</th><td>undefined method `delete&#39; for nil:NilClass</td></tr><tr><th>Last Occurrence</th><td>September 07, 2017 19:06:09 +0530</td></tr><tr><th>Count</th><td>5</td></tr></table>

## Stack Trace
<pre><a href='https://github.com/tannakartikey/currents/blob/46df39debc8dc6f93298cb55110b6a34ea6cb444/app/models/stripe_subscription.rb#L17'>[app].../app/models/stripe_subscription.rb:17:in `delete'</a>
<a href='https://github.com/tannakartikey/currents/blob/46df39debc8dc6f93298cb55110b6a34ea6cb444/app/models/exception_wrapper.rb#L11'>[app].../app/models/exception_wrapper.rb:11:in `call'</a>
<a href='https://github.com/tannakartikey/currents/blob/46df39debc8dc6f93298cb55110b6a34ea6cb444/app/models/exception_wrapper.rb#L11'>[app].../app/models/exception_wrapper.rb:11:in `block (2 levels) in singleton class'</a>
(pry):4:in `block in <main>'
[bundle].../gems/activerecord-4.2.7.1/lib/active_record/relation/delegation.rb:46:in `each'
[bundle].../gems/activerecord-4.2.7.1/lib/active_record/relation/delegation.rb:46:in `each'
(pry):3:in `<main>'
[bundle].../gems/pry-0.10.4/lib/pry/pry_instance.rb:355:in `eval'
[bundle].../gems/pry-0.10.4/lib/pry/pry_instance.rb:355:in `evaluate_ruby'
[bundle].../gems/pry-0.10.4/lib/pry/pry_instance.rb:323:in `handle_line'
[bundle].../gems/pry-0.10.4/lib/pry/pry_instance.rb:243:in `block (2 levels) in eval'
[bundle].../gems/pry-0.10.4/lib/pry/pry_instance.rb:242:in `catch'
[bundle].../gems/pry-0.10.4/lib/pry/pry_instance.rb:242:in `block in eval'
[bundle].../gems/pry-0.10.4/lib/pry/pry_instance.rb:241:in `catch'
[bundle].../gems/pry-0.10.4/lib/pry/pry_instance.rb:241:in `eval'
[bundle].../gems/pry-0.10.4/lib/pry/repl.rb:77:in `block in repl'
[bundle].../gems/pry-0.10.4/lib/pry/repl.rb:67:in `loop'
[bundle].../gems/pry-0.10.4/lib/pry/repl.rb:67:in `repl'
[bundle].../gems/pry-0.10.4/lib/pry/repl.rb:38:in `block in start'
[bundle].../gems/pry-0.10.4/lib/pry/input_lock.rb:61:in `__with_ownership'
[bundle].../gems/pry-0.10.4/lib/pry/input_lock.rb:79:in `with_ownership'
[bundle].../gems/pry-0.10.4/lib/pry/repl.rb:38:in `start'
[bundle].../gems/pry-0.10.4/lib/pry/repl.rb:15:in `start'
[bundle].../gems/pry-0.10.4/lib/pry/pry_class.rb:169:in `start'
[bundle].../gems/pry-byebug-3.4.2/lib/pry-byebug/pry_ext.rb:11:in `start_with_pry_byebug'
[bundle].../gems/railties-4.2.7.1/lib/rails/commands/console.rb:110:in `start'
[bundle].../gems/railties-4.2.7.1/lib/rails/commands/console.rb:9:in `start'
[bundle].../gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:68:in `console'
[bundle].../gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
[bundle].../gems/railties-4.2.7.1/lib/rails/commands.rb:17:in `<top (required)>'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
<a href='https://github.com/tannakartikey/currents/blob/46df39debc8dc6f93298cb55110b6a34ea6cb444/bin/rails#L9'>[app].../bin/rails:9:in `<top (required)>'</a>
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `block in load'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
[bundle].../gems/spring-2.0.2/lib/spring/commands/rails.rb:6:in `call'
[bundle].../gems/spring-2.0.2/lib/spring/command_wrapper.rb:38:in `call'
[bundle].../gems/spring-2.0.2/lib/spring/application.rb:201:in `block in serve'
[bundle].../gems/spring-2.0.2/lib/spring/application.rb:171:in `fork'
[bundle].../gems/spring-2.0.2/lib/spring/application.rb:171:in `serve'
[bundle].../gems/spring-2.0.2/lib/spring/application.rb:141:in `block in run'
[bundle].../gems/spring-2.0.2/lib/spring/application.rb:135:in `loop'
[bundle].../gems/spring-2.0.2/lib/spring/application.rb:135:in `run'
[bundle].../gems/spring-2.0.2/lib/spring/application/boot.rb:19:in `<top (required)>'
/home/kartikey/.rbenv/versions/2.3.4/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/home/kartikey/.rbenv/versions/2.3.4/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
-e:1:in `<main>'</pre>
Fingerprint: `1656fb687d5807aeee670978196fda7a96193c19`

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 29, 2017 23:57:37 +0530</td></tr><tr><th>Params</th><td>#&lt;User id: 3, email: &quot;enda@heller.co.uk&quot;, created_at: &quot;2017-08-04 09:07:52&quot;, updated_at: &quot;2017-08-29 17:39:16&quot;, first_name: nil, last_name: nil, home_port: nil, state_waters: &quot;MA&quot;, vessel_name: nil, subscription_tier: nil, stripe_customer_id: &quot;cus_BG2Ixm2HtkUpdR&quot;, subscription_id: nil, is_active: false, payment_source: nil, deleted_at: nil&gt;</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 29, 2017 23:57:51 +0530</td></tr><tr><th>Params</th><td>#&lt;User id: 15, email: &quot;testemail2@mailinator.com&quot;, created_at: &quot;2017-08-06 12:16:06&quot;, updated_at: &quot;2017-08-29 17:39:22&quot;, first_name: nil, last_name: nil, home_port: nil, state_waters: &quot;MA&quot;, vessel_name: nil, subscription_tier: nil, stripe_customer_id: &quot;cus_BG2JHQdMPOto7J&quot;, subscription_id: nil, is_active: false, payment_source: nil, deleted_at: nil&gt;</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>September 07, 2017 19:00:53 +0530</td></tr><tr><th>Params</th><td>#&lt;User id: 12, email: &quot;tannakartikey@gmail.com&quot;, created_at: &quot;2017-08-05 15:28:27&quot;, updated_at: &quot;2017-09-07 13:09:23&quot;, first_name: nil, last_name: nil, home_port: nil, state_waters: &quot;MA&quot;, vessel_name: nil, subscription_tier: nil, stripe_customer_id: &quot;cus_BJ1cLzc7y1qKmK&quot;, subscription_id: nil, is_active: true, payment_source: nil, deleted_at: nil&gt;</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>September 07, 2017 19:03:36 +0530</td></tr><tr><th>Params</th><td>#&lt;User id: 12, email: &quot;tannakartikey@gmail.com&quot;, created_at: &quot;2017-08-05 15:28:27&quot;, updated_at: &quot;2017-09-07 13:09:23&quot;, first_name: nil, last_name: nil, home_port: nil, state_waters: &quot;MA&quot;, vessel_name: nil, subscription_tier: nil, stripe_customer_id: &quot;cus_BJ1cLzc7y1qKmK&quot;, subscription_id: nil, is_active: true, payment_source: nil, deleted_at: nil&gt;</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>September 07, 2017 19:06:09 +0530</td></tr><tr><th>Params</th><td>#&lt;User id: 12, email: &quot;tannakartikey@gmail.com&quot;, created_at: &quot;2017-08-05 15:28:27&quot;, updated_at: &quot;2017-09-07 13:09:23&quot;, first_name: nil, last_name: nil, home_port: nil, state_waters: &quot;MA&quot;, vessel_name: nil, subscription_tier: nil, stripe_customer_id: &quot;cus_BJ1cLzc7y1qKmK&quot;, subscription_id: nil, is_active: true, payment_source: nil, deleted_at: nil&gt;</td></tr></table>
