### ISSUE TITLE
#<StripeController:0xXXXXXX>#events (TypeError) "no implicit conversion of String into Integer"

### ISSUE THREAD

**Issue by tannakartikey** [tannakartikey/currents#300]
<table><tr><th>Exception</th><td>no implicit conversion of String into Integer</td></tr><tr><th>Last Occurrence</th><td>August 31, 2017 23:10:44 +0530</td></tr><tr><th>Count</th><td>2</td></tr></table>

## Stack Trace
<pre><a href='https://github.com/tannakartikey/currents/blob/53c0342e343f53b943b686fbe1e1cb77a5b6e7a1/app/controllers/stripe_controller.rb#L21'>[app].../app/controllers/stripe_controller.rb:21:in `[]'</a>
<a href='https://github.com/tannakartikey/currents/blob/53c0342e343f53b943b686fbe1e1cb77a5b6e7a1/app/controllers/stripe_controller.rb#L21'>[app].../app/controllers/stripe_controller.rb:21:in `block in events'</a></pre>
Fingerprint: `3111ede1f269c4963fdcac74f17a24f900596500`

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 31, 2017 23:10:14 +0530</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 31, 2017 23:10:44 +0530</td></tr><tr><th>Params</th><td></td></tr></table>
