### ISSUE TITLE
#<StripeController:0xXXXXXX>#events (ActionView::Template::Error) "Missing partial layouts/_mailer_header with {:locale=>[:en], :formats=>[:html], :variants=>[], :handlers=>[:erb, :builder, :raw, :ruby, :coffee, :arb, :jbuilder]}. Searched in:
  * "/media/kartikey/volume_2/Source/currents/app/views"
  * "/home/kartikey/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-21c50cafc5bf/app/views"
  * "/home/kartikey/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/kaminari-core-1.0.1/app/views"
  * "/home/kartikey/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/devise-4.3.0/app/views"
"

### ISSUE THREAD

**Issue by tannakartikey** [tannakartikey/currents#304]
<table><tr><th>Exception</th><td>Missing partial layouts/_mailer_header with {:locale=&gt;[:en], :formats=&gt;[:html], :variants=&gt;[], :handlers=&gt;[:erb, :builder, :raw, :ruby, :coffee, :arb, :jbuilder]}. Searched in:
  * &quot;/media/kartikey/volume_2/Source/currents/app/views&quot;
  * &quot;/home/kartikey/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/bundler/gems/activeadmin-21c50cafc5bf/app/views&quot;
  * &quot;/home/kartikey/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/kaminari-core-1.0.1/app/views&quot;
  * &quot;/home/kartikey/.rbenv/versions/2.3.4/lib/ruby/gems/2.3.0/gems/devise-4.3.0/app/views&quot;
</td></tr><tr><th>Last Occurrence</th><td>September 01, 2017 00:56:55 +0530</td></tr><tr><th>Count</th><td>1</td></tr></table>

## Stack Trace
<pre>[bundle].../gems/actionview-4.2.7.1/lib/action_view/path_set.rb:46:in `find'
[bundle].../gems/actionview-4.2.7.1/lib/action_view/lookup_context.rb:121:in `find'
[bundle].../gems/actionview-4.2.7.1/lib/action_view/renderer/partial_renderer.rb:418:in `find_template'
[bundle].../gems/actionview-4.2.7.1/lib/action_view/renderer/partial_renderer.rb:413:in `find_partial'
[bundle].../gems/actionview-4.2.7.1/lib/action_view/renderer/partial_renderer.rb:294:in `render'
[bundle].../gems/actionview-4.2.7.1/lib/action_view/renderer/renderer.rb:51:in `render_partial'
[bundle].../gems/actionview-4.2.7.1/lib/action_view/helpers/rendering_helper.rb:35:in `render'
<a href='https://github.com/tannakartikey/currents/blob/53c0342e343f53b943b686fbe1e1cb77a5b6e7a1/app/views/subscription_mailer/charge_failed.html.erb#L1'>[app].../app/views/subscription_mailer/charge_failed.html.erb:1:in `_app_views_subscription_mailer_charge_failed_html_erb__1726808846337546813_69916701178940'</a>
[bundle].../gems/actionview-4.2.7.1/lib/action_view/template.rb:145:in `block in render'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:166:in `instrument'
[bundle].../gems/actionview-4.2.7.1/lib/action_view/template.rb:333:in `instrument'
[bundle].../gems/actionview-4.2.7.1/lib/action_view/template.rb:143:in `render'
[bundle].../gems/actionview-4.2.7.1/lib/action_view/renderer/template_renderer.rb:54:in `block (2 levels) in render_template'
[bundle].../gems/actionview-4.2.7.1/lib/action_view/renderer/abstract_renderer.rb:39:in `block in instrument'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `block in instrument'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `instrument'
[bundle].../gems/actionview-4.2.7.1/lib/action_view/renderer/abstract_renderer.rb:39:in `instrument'
[bundle].../gems/actionview-4.2.7.1/lib/action_view/renderer/template_renderer.rb:53:in `block in render_template'
[bundle].../gems/actionview-4.2.7.1/lib/action_view/renderer/template_renderer.rb:61:in `render_with_layout'
[bundle].../gems/actionview-4.2.7.1/lib/action_view/renderer/template_renderer.rb:52:in `render_template'
[bundle].../gems/actionview-4.2.7.1/lib/action_view/renderer/template_renderer.rb:14:in `render'
[bundle].../gems/actionview-4.2.7.1/lib/action_view/renderer/renderer.rb:46:in `render_template'
[bundle].../gems/actionview-4.2.7.1/lib/action_view/renderer/renderer.rb:27:in `render'
[bundle].../gems/actionview-4.2.7.1/lib/action_view/rendering.rb:100:in `_render_template'
[bundle].../gems/actionview-4.2.7.1/lib/action_view/rendering.rb:83:in `render_to_body'
[bundle].../gems/actionpack-4.2.7.1/lib/abstract_controller/rendering.rb:25:in `render'
[bundle].../gems/actionmailer-4.2.7.1/lib/action_mailer/base.rb:904:in `block in collect_responses'
[bundle].../gems/actionmailer-4.2.7.1/lib/action_mailer/base.rb:918:in `each'
[bundle].../gems/actionmailer-4.2.7.1/lib/action_mailer/base.rb:918:in `each_template'
[bundle].../gems/actionmailer-4.2.7.1/lib/action_mailer/base.rb:900:in `collect_responses'
[bundle].../gems/actionmailer-4.2.7.1/lib/action_mailer/base.rb:829:in `mail'
<a href='https://github.com/tannakartikey/currents/blob/53c0342e343f53b943b686fbe1e1cb77a5b6e7a1/app/mailers/subscription_mailer.rb#L43'>[app].../app/mailers/subscription_mailer.rb:43:in `charge_failed'</a>
[bundle].../gems/actionpack-4.2.7.1/lib/abstract_controller/base.rb:198:in `process_action'
[bundle].../gems/actionpack-4.2.7.1/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
[bundle].../gems/actionpack-4.2.7.1/lib/abstract_controller/callbacks.rb:19:in `process_action'
[bundle].../gems/actionpack-4.2.7.1/lib/abstract_controller/base.rb:137:in `process'
[bundle].../gems/actionview-4.2.7.1/lib/action_view/rendering.rb:30:in `process'
[bundle].../gems/actionmailer-4.2.7.1/lib/action_mailer/base.rb:596:in `block in process'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `block in instrument'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `instrument'
[bundle].../gems/actionmailer-4.2.7.1/lib/action_mailer/base.rb:593:in `process'
[bundle].../gems/actionmailer-4.2.7.1/lib/action_mailer/base.rb:584:in `initialize'
[bundle].../gems/actionmailer-4.2.7.1/lib/action_mailer/message_delivery.rb:25:in `new'
[bundle].../gems/actionmailer-4.2.7.1/lib/action_mailer/message_delivery.rb:25:in `__getobj__'
[bundle].../gems/actionmailer-4.2.7.1/lib/action_mailer/message_delivery.rb:34:in `message'
[bundle].../gems/actionmailer-4.2.7.1/lib/action_mailer/message_delivery.rb:85:in `deliver_now'
[bundle].../gems/actionmailer-4.2.7.1/lib/action_mailer/message_delivery.rb:105:in `deliver'
<a href='https://github.com/tannakartikey/currents/blob/53c0342e343f53b943b686fbe1e1cb77a5b6e7a1/app/controllers/stripe_controller.rb#L79'>[app].../app/controllers/stripe_controller.rb:79:in `event_process'</a>
<a href='https://github.com/tannakartikey/currents/blob/53c0342e343f53b943b686fbe1e1cb77a5b6e7a1/app/controllers/stripe_controller.rb#L20'>[app].../app/controllers/stripe_controller.rb:20:in `block in events'</a></pre>
Fingerprint: `479a1cc9df0bb9ef259b0451b7ca6d930beca84d`

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>September 01, 2017 00:56:55 +0530</td></tr><tr><th>Params</th><td>#&lt;User:0x007f2d803f1218&gt;</td></tr></table>
