### ISSUE TITLE
#<StripeController:0xXXXXXX>#events (JSON::GeneratorError) "only generation of JSON objects or arrays allowed"

### ISSUE THREAD

**Issue by tannakartikey** [tannakartikey/currents#315]
<table><tr><th>Exception</th><td>only generation of JSON objects or arrays allowed</td></tr><tr><th>Last Occurrence</th><td>September 02, 2017 16:32:57 +0530</td></tr><tr><th>Count</th><td>5</td></tr></table>

## Stack Trace
<pre>[bundle].../gems/json-1.8.6/lib/json/common.rb:285:in `generate'
[bundle].../gems/json-1.8.6/lib/json/common.rb:285:in `pretty_generate'
<a href='https://github.com/tannakartikey/currents/blob/c2507397776c529a36cdddfeabf342044851f826/app/mailers/other_events_mailer.rb#L6'>[app].../app/mailers/other_events_mailer.rb:6:in `notify'</a>
[bundle].../gems/actionpack-4.2.7.1/lib/abstract_controller/base.rb:198:in `process_action'
[bundle].../gems/actionpack-4.2.7.1/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
[bundle].../gems/actionpack-4.2.7.1/lib/abstract_controller/callbacks.rb:19:in `process_action'
[bundle].../gems/actionpack-4.2.7.1/lib/abstract_controller/base.rb:137:in `process'
[bundle].../gems/actionview-4.2.7.1/lib/action_view/rendering.rb:30:in `process'
[bundle].../gems/actionmailer-4.2.7.1/lib/action_mailer/base.rb:596:in `block in process'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `block in instrument'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `instrument'
[bundle].../gems/actionmailer-4.2.7.1/lib/action_mailer/base.rb:593:in `process'
[bundle].../gems/actionmailer-4.2.7.1/lib/action_mailer/base.rb:584:in `initialize'
[bundle].../gems/actionmailer-4.2.7.1/lib/action_mailer/message_delivery.rb:25:in `new'
[bundle].../gems/actionmailer-4.2.7.1/lib/action_mailer/message_delivery.rb:25:in `__getobj__'
[bundle].../gems/actionmailer-4.2.7.1/lib/action_mailer/message_delivery.rb:34:in `message'
[bundle].../gems/actionmailer-4.2.7.1/lib/action_mailer/message_delivery.rb:85:in `deliver_now'
[bundle].../gems/actionmailer-4.2.7.1/lib/action_mailer/message_delivery.rb:105:in `deliver'
<a href='https://github.com/tannakartikey/currents/blob/c2507397776c529a36cdddfeabf342044851f826/app/controllers/stripe_controller.rb#L101'>[app].../app/controllers/stripe_controller.rb:101:in `event_process'</a>
<a href='https://github.com/tannakartikey/currents/blob/c2507397776c529a36cdddfeabf342044851f826/app/controllers/stripe_controller.rb#L24'>[app].../app/controllers/stripe_controller.rb:24:in `block in events'</a></pre>
Fingerprint: `e57e23f9748e5bd1bafb627dc343a7a397035a1b`

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>September 02, 2017 16:25:37 +0530</td></tr><tr><th>Params</th><td>#&lt;User:0x007f96acd962d8&gt;</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>September 02, 2017 16:26:23 +0530</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>September 02, 2017 16:26:29 +0530</td></tr><tr><th>Params</th><td>#&lt;User:0x007f969c056330&gt;</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>September 02, 2017 16:28:21 +0530</td></tr><tr><th>Params</th><td>#&lt;User:0x007f96cb1f8f60&gt;</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>September 02, 2017 16:28:24 +0530</td></tr><tr><th>Params</th><td>#&lt;User:0x007f96cb0f88b8&gt;</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>September 02, 2017 16:28:25 +0530</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>September 02, 2017 16:32:57 +0530</td></tr><tr><th>Params</th><td></td></tr></table>
