### ISSUE TITLE
#<StripeController:0xXXXXXX>#events (NoMethodError) "undefined method `status' for nil:NilClass"

### ISSUE THREAD

**Issue by tannakartikey** [tannakartikey/currents#317]
<table><tr><th>Exception</th><td>undefined method `status&#39; for nil:NilClass</td></tr><tr><th>Last Occurrence</th><td>September 04, 2017 11:29:04 +0530</td></tr><tr><th>Count</th><td>8</td></tr></table>

## Stack Trace
<pre><a href='https://github.com/tannakartikey/currents/blob/c2507397776c529a36cdddfeabf342044851f826/app/controllers/stripe_controller.rb#L51'>[app].../app/controllers/stripe_controller.rb:51:in `event_process'</a>
<a href='https://github.com/tannakartikey/currents/blob/c2507397776c529a36cdddfeabf342044851f826/app/controllers/stripe_controller.rb#L24'>[app].../app/controllers/stripe_controller.rb:24:in `block in events'</a></pre>
Fingerprint: `7683ec816cac946cb3c0003bd55542991950aadf`

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>September 02, 2017 16:26:00 +0530</td></tr><tr><th>Params</th><td>#&lt;User:0x007f96ac8360e0&gt;</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>September 02, 2017 16:28:39 +0530</td></tr><tr><th>Params</th><td>#&lt;User:0x000051535b5de8&gt;</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>September 02, 2017 16:51:31 +0530</td></tr><tr><th>Params</th><td>#&lt;User:0x00008b2e2170a0&gt;</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>September 02, 2017 16:55:09 +0530</td></tr><tr><th>Params</th><td>#&lt;User:0x00008b2df80760&gt;</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>September 03, 2017 23:37:40 +0530</td></tr><tr><th>Params</th><td>#&lt;User:0x007f198c0d9c68&gt;</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>September 04, 2017 00:22:28 +0530</td></tr><tr><th>Params</th><td>#&lt;User:0x007f19a007a1c8&gt;</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>September 04, 2017 10:31:13 +0530</td></tr><tr><th>Params</th><td>#&lt;User:0x000095e36a3e38&gt;</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>September 04, 2017 11:29:04 +0530</td></tr><tr><th>Params</th><td>#&lt;User:0x000095e35103c8&gt;</td></tr></table>
