### ISSUE TITLE
#<StripeController:0xXXXXXX>#events (NoMethodError) "undefined method `trial_end' for #<Stripe::StripeObject:0xXXXXXX>"

### ISSUE THREAD

**Issue by tannakartikey** [tannakartikey/currents#318]
<table><tr><th>Exception</th><td>undefined method `trial_end&#39; for #&lt;Stripe::StripeObject:0x00005265d11430&gt;</td></tr><tr><th>Last Occurrence</th><td>May 10, 2018 02:21:56 +0000</td></tr><tr><th>Count</th><td>43</td></tr></table>

## Stack Trace
<pre>[bundle].../gems/stripe-3.0.0/lib/stripe/stripe_object.rb:285:in `method_missing'
<a href='https://github.com/tannakartikey/currents/blob/c2507397776c529a36cdddfeabf342044851f826/app/controllers/stripe_controller.rb#L62'>[app].../app/controllers/stripe_controller.rb:62:in `event_process'</a>
<a href='https://github.com/tannakartikey/currents/blob/c2507397776c529a36cdddfeabf342044851f826/app/controllers/stripe_controller.rb#L24'>[app].../app/controllers/stripe_controller.rb:24:in `block in events'</a></pre>
Fingerprint: `b9638edd83eb81f9c3103f86586fcac4f64236ea`

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>September 02, 2017 17:02:42 +0530</td></tr><tr><th>Params</th><td>#&lt;User:0x000052657f0140&gt;</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>September 02, 2017 17:04:18 +0530</td></tr><tr><th>Params</th><td>#&lt;User:0x000052657e0b28&gt;</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>September 02, 2017 23:38:14 +0530</td></tr><tr><th>Params</th><td>#&lt;User:0x00005265b37d58&gt;</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>September 02, 2017 23:45:09 +0530</td></tr><tr><th>Params</th><td>#&lt;User:0x007f1ef065ee90&gt;</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>September 02, 2017 23:58:27 +0530</td></tr><tr><th>Params</th><td>#&lt;User:0x007f1ef8672640&gt;</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>September 03, 2017 00:03:00 +0530</td></tr><tr><th>Params</th><td>#&lt;User:0x0000a894dc07e8&gt;</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>September 03, 2017 00:03:51 +0530</td></tr><tr><th>Params</th><td>#&lt;User:0x0000a89574cc58&gt;</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>September 03, 2017 00:05:03 +0530</td></tr><tr><th>Params</th><td>#&lt;User:0x007f1e5c7bdbe0&gt;</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>September 11, 2017 06:28:40 +0000</td></tr><tr><th>Params</th><td>#&lt;User id: 4, email: &quot;tannakartikey@gmail.com&quot;, created_at: &quot;2017-07-08 08:57:30&quot;, updated_at: &quot;2017-09-11 05:28:23&quot;, first_name: &quot;Kartikey&quot;, last_name: &quot;Tanna&quot;, home_port: &quot;&quot;, state_waters: &quot;CT&quot;, vessel_name: &quot;&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_BNVFg1D9JuGkfz&quot;, subscription_id: &quot;sub_BNVNmQPYEn3xqH&quot;, is_active: false, payment_source: nil, deleted_at: nil&gt;</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>March 11, 2018 02:46:19 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 17, email: &quot;ajcosta1@gmail.com&quot;, created_at: &quot;2018-02-08 15:04:23&quot;, updated_at: &quot;2018-03-11 00:04:58&quot;, first_name: &quot;Tim&quot;, last_name: &quot;Brady&quot;, home_port: &quot;Plymouth&quot;, state_waters: &quot;MA&quot;, vessel_name: &quot;ALKJASDFJALKSDJFLAKSDJFLKASJDFKLAJSDKLFJALSKDJFAF&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_CHqe6cGe6WXt02&quot;, subscription_id: &quot;sub_CHqeTiXLRk8Llg&quot;, is_active: false, payment_source: nil, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>customer.subscription.updated</td></tr><tr><th>event_id</th><td>evt_1C4KCODyDCrOMJ6PHFZD9iuL</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 01, 2018 01:19:43 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 19, email: &quot;email1@gmail.abc&quot;, created_at: &quot;2018-03-01 09:49:19&quot;, updated_at: &quot;2018-04-01 00:18:54&quot;, first_name: &quot;Test&quot;, last_name: &quot;Email1&quot;, home_port: &quot;&quot;, state_waters: &quot;MA&quot;, vessel_name: &quot;&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_CPdJ2VQs0AdRQw&quot;, subscription_id: &quot;sub_CPdJ1qfPG0Cswt&quot;, is_active: false, payment_source: nil, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>customer.subscription.updated</td></tr><tr><th>event_id</th><td>evt_1CBuqhDyDCrOMJ6Pjd2IzDgz</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 02, 2018 01:06:01 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 24, email: &quot;dobi@gmail.com&quot;, created_at: &quot;2018-03-02 11:06:56&quot;, updated_at: &quot;2018-04-02 00:05:49&quot;, first_name: &quot;&quot;, last_name: &quot;&quot;, home_port: &quot;Iusto et illum ex vel&quot;, state_waters: &quot;NY&quot;, vessel_name: &quot;Adena Duffy&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_CQ1mgE6R2bQsP0&quot;, subscription_id: &quot;sub_CQ1mCArDFpuX5B&quot;, is_active: false, payment_source: nil, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>customer.subscription.updated</td></tr><tr><th>event_id</th><td>evt_1CCH7ODyDCrOMJ6PWcGFPcG6</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 02, 2018 01:07:14 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 21, email: &quot;user3@gmail.com&quot;, created_at: &quot;2018-03-02 05:41:47&quot;, updated_at: &quot;2018-04-02 00:08:06&quot;, first_name: &quot;&quot;, last_name: &quot;&quot;, home_port: &quot;&quot;, state_waters: &quot;MA&quot;, vessel_name: &quot;&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_CPwXKL5Djqh0jn&quot;, subscription_id: &quot;sub_CPwXox8lVT6p7I&quot;, is_active: false, payment_source: nil, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>customer.subscription.updated</td></tr><tr><th>event_id</th><td>evt_1CCH7TDyDCrOMJ6P9JOv9tiL</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 02, 2018 01:08:51 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 22, email: &quot;user11@gmail.com&quot;, created_at: &quot;2018-03-02 05:45:19&quot;, updated_at: &quot;2018-04-02 00:07:42&quot;, first_name: &quot;abc&quot;, last_name: &quot;def&quot;, home_port: &quot;&quot;, state_waters: &quot;MA&quot;, vessel_name: &quot;&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_CPwboQWmeMwlBV&quot;, subscription_id: &quot;sub_CPwb5lBvjkM1u4&quot;, is_active: false, payment_source: nil, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>customer.subscription.updated</td></tr><tr><th>event_id</th><td>evt_1CCH93DyDCrOMJ6P6tkwBa50</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 02, 2018 01:37:00 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 20, email: &quot;user2@gmail.com&quot;, created_at: &quot;2018-03-02 05:37:46&quot;, updated_at: &quot;2018-04-02 00:05:49&quot;, first_name: &quot;&quot;, last_name: &quot;&quot;, home_port: &quot;&quot;, state_waters: &quot;MA&quot;, vessel_name: &quot;&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_CPwT9IarIhliCS&quot;, subscription_id: &quot;sub_CPwTEC07SgUk35&quot;, is_active: false, payment_source: nil, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>customer.subscription.updated</td></tr><tr><th>event_id</th><td>evt_1CCHbPDyDCrOMJ6Pep6QHAux</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 02, 2018 02:18:31 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 23, email: &quot;cykumocyz@gmail.com&quot;, created_at: &quot;2018-03-02 11:06:10&quot;, updated_at: &quot;2018-04-02 00:07:00&quot;, first_name: &quot;Chloe&quot;, last_name: &quot;Elliott&quot;, home_port: &quot;Sint voluptas reiciendis amet et excepteur consect...&quot;, state_waters: &quot;RI&quot;, vessel_name: &quot;Berk Camacho&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_CQ1l94iHFQrDxX&quot;, subscription_id: &quot;sub_CQ1l1xFvfVPH1l&quot;, is_active: false, payment_source: nil, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>customer.subscription.updated</td></tr><tr><th>event_id</th><td>evt_1CCIFCDyDCrOMJ6Pi5b9bGx2</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 08, 2018 01:11:05 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 26, email: &quot;completetest4@email.com&quot;, created_at: &quot;2018-03-08 10:23:37&quot;, updated_at: &quot;2018-04-08 00:10:32&quot;, first_name: &quot;Complete&quot;, last_name: &quot;Test 4&quot;, home_port: &quot;&quot;, state_waters: &quot;MA&quot;, vessel_name: &quot;&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_CSGRXlQ96YkqAd&quot;, subscription_id: &quot;sub_CSGRm9HVUruxMh&quot;, is_active: false, payment_source: nil, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>customer.subscription.updated</td></tr><tr><th>event_id</th><td>evt_1CES3DDyDCrOMJ6PraUkQfcE</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 10, 2018 01:04:06 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 29, email: &quot;completetest8@email.com&quot;, created_at: &quot;2018-03-10 06:08:12&quot;, updated_at: &quot;2018-04-10 00:02:30&quot;, first_name: &quot;Complete&quot;, last_name: &quot;Test 8&quot;, home_port: &quot;&quot;, state_waters: &quot;MA&quot;, vessel_name: &quot;&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_CSwlShY8D5ogwo&quot;, subscription_id: &quot;sub_CSwlW66kMtnzxu&quot;, is_active: false, payment_source: nil, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>customer.subscription.updated</td></tr><tr><th>event_id</th><td>evt_1CFAtRDyDCrOMJ6PrvTvyntr</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 10, 2018 01:04:06 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 27, email: &quot;completetest6@email.com&quot;, created_at: &quot;2018-03-10 05:46:08&quot;, updated_at: &quot;2018-04-10 00:02:30&quot;, first_name: &quot;Complete&quot;, last_name: &quot;Test 6&quot;, home_port: &quot;&quot;, state_waters: &quot;MA&quot;, vessel_name: &quot;&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_CSwPcuS8sdUHkm&quot;, subscription_id: &quot;sub_CSwPOsUwQrWRII&quot;, is_active: false, payment_source: nil, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>customer.subscription.updated</td></tr><tr><th>event_id</th><td>evt_1CFAtSDyDCrOMJ6P6GqSHT9j</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 10, 2018 01:04:06 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 28, email: &quot;completetest7@email.com&quot;, created_at: &quot;2018-03-10 05:53:32&quot;, updated_at: &quot;2018-04-10 00:02:29&quot;, first_name: &quot;Complete&quot;, last_name: &quot;Test 7&quot;, home_port: &quot;&quot;, state_waters: &quot;MA&quot;, vessel_name: &quot;&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_CSwXUVAYqy70ME&quot;, subscription_id: &quot;sub_CSwXNs6unrafzK&quot;, is_active: false, payment_source: nil, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>customer.subscription.updated</td></tr><tr><th>event_id</th><td>evt_1CFAtRDyDCrOMJ6PzN5Ra06T</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 10, 2018 01:41:42 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 27, email: &quot;completetest6@email.com&quot;, created_at: &quot;2018-03-10 05:46:08&quot;, updated_at: &quot;2018-04-10 00:02:30&quot;, first_name: &quot;Complete&quot;, last_name: &quot;Test 6&quot;, home_port: &quot;&quot;, state_waters: &quot;MA&quot;, vessel_name: &quot;&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_CSwPcuS8sdUHkm&quot;, subscription_id: &quot;sub_CSwPOsUwQrWRII&quot;, is_active: false, payment_source: nil, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>customer.subscription.updated</td></tr><tr><th>event_id</th><td>evt_1CFAtSDyDCrOMJ6P6GqSHT9j</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 10, 2018 01:46:42 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 29, email: &quot;completetest8@email.com&quot;, created_at: &quot;2018-03-10 06:08:12&quot;, updated_at: &quot;2018-04-10 00:02:30&quot;, first_name: &quot;Complete&quot;, last_name: &quot;Test 8&quot;, home_port: &quot;&quot;, state_waters: &quot;MA&quot;, vessel_name: &quot;&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_CSwlShY8D5ogwo&quot;, subscription_id: &quot;sub_CSwlW66kMtnzxu&quot;, is_active: false, payment_source: nil, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>customer.subscription.updated</td></tr><tr><th>event_id</th><td>evt_1CFAtRDyDCrOMJ6PrvTvyntr</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 10, 2018 02:03:16 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 28, email: &quot;completetest7@email.com&quot;, created_at: &quot;2018-03-10 05:53:32&quot;, updated_at: &quot;2018-04-10 00:02:29&quot;, first_name: &quot;Complete&quot;, last_name: &quot;Test 7&quot;, home_port: &quot;&quot;, state_waters: &quot;MA&quot;, vessel_name: &quot;&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_CSwXUVAYqy70ME&quot;, subscription_id: &quot;sub_CSwXNs6unrafzK&quot;, is_active: false, payment_source: nil, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>customer.subscription.updated</td></tr><tr><th>event_id</th><td>evt_1CFAtRDyDCrOMJ6PzN5Ra06T</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 16, 2018 02:28:14 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 30, email: &quot;useremailtest1@email.com&quot;, created_at: &quot;2018-03-16 15:48:32&quot;, updated_at: &quot;2018-04-16 00:01:47&quot;, first_name: &quot;First&quot;, last_name: &quot;Last&quot;, home_port: &quot;&quot;, state_waters: &quot;MA&quot;, vessel_name: &quot;&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_CVLUUSz4hjDFWs&quot;, subscription_id: &quot;sub_CVLUbjdGUA25LJ&quot;, is_active: false, payment_source: nil, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>customer.subscription.updated</td></tr><tr><th>event_id</th><td>evt_1CHN41DyDCrOMJ6PwdF3EsLQ</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 16, 2018 03:07:45 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 30, email: &quot;useremailtest1@email.com&quot;, created_at: &quot;2018-03-16 15:48:32&quot;, updated_at: &quot;2018-04-16 00:01:47&quot;, first_name: &quot;First&quot;, last_name: &quot;Last&quot;, home_port: &quot;&quot;, state_waters: &quot;MA&quot;, vessel_name: &quot;&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_CVLUUSz4hjDFWs&quot;, subscription_id: &quot;sub_CVLUbjdGUA25LJ&quot;, is_active: false, payment_source: nil, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>customer.subscription.updated</td></tr><tr><th>event_id</th><td>evt_1CHN41DyDCrOMJ6PwdF3EsLQ</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 20, 2018 03:33:12 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>customer.subscription.updated</td></tr><tr><th>event_id</th><td>evt_1CIpzmDyDCrOMJ6PafISJT2l</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 23, 2018 21:03:32 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>customer.subscription.updated</td></tr><tr><th>event_id</th><td>evt_1CKBoIDyDCrOMJ6PQEAjKup1</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 23, 2018 22:12:48 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>customer.subscription.updated</td></tr><tr><th>event_id</th><td>evt_1CKBoIDyDCrOMJ6PQEAjKup1</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 24, 2018 02:27:50 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>customer.subscription.updated</td></tr><tr><th>event_id</th><td>evt_1CKGshDyDCrOMJ6PtoF5c4n6</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>May 03, 2018 04:03:39 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>customer.subscription.updated</td></tr><tr><th>event_id</th><td>evt_1CNYelDyDCrOMJ6PYQlno79H</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>May 03, 2018 05:03:10 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>customer.subscription.updated</td></tr><tr><th>event_id</th><td>evt_1CNYelDyDCrOMJ6PYQlno79H</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>May 10, 2018 01:03:33 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>customer.subscription.updated</td></tr><tr><th>event_id</th><td>evt_1CQ3BJDyDCrOMJ6P1fxIkE14</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>May 10, 2018 02:21:56 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>customer.subscription.updated</td></tr><tr><th>event_id</th><td>evt_1CQ3BJDyDCrOMJ6P1fxIkE14</td></tr></table></td></tr></table>
