### ISSUE TITLE
#<StripeController:0xXXXXXX>#events (TypeError) "no implicit conversion of nil into String"

### ISSUE THREAD

**Issue by tannakartikey** [tannakartikey/currents#319]
<table><tr><th>Exception</th><td>no implicit conversion of nil into String</td></tr><tr><th>Last Occurrence</th><td>September 04, 2017 12:49:50 +0530</td></tr><tr><th>Count</th><td>9</td></tr></table>

## Stack Trace
<pre><a href='https://github.com/tannakartikey/currents/blob/c2507397776c529a36cdddfeabf342044851f826/app/controllers/stripe_controller.rb#L62'>[app].../app/controllers/stripe_controller.rb:62:in `strptime'</a>
<a href='https://github.com/tannakartikey/currents/blob/c2507397776c529a36cdddfeabf342044851f826/app/controllers/stripe_controller.rb#L62'>[app].../app/controllers/stripe_controller.rb:62:in `event_process'</a>
<a href='https://github.com/tannakartikey/currents/blob/c2507397776c529a36cdddfeabf342044851f826/app/controllers/stripe_controller.rb#L24'>[app].../app/controllers/stripe_controller.rb:24:in `block in events'</a></pre>
Fingerprint: `697907d3e196f4228b8b4fdc2483595548105fc2`

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>September 04, 2017 11:54:01 +0530</td></tr><tr><th>Params</th><td>#&lt;User:0x007f39683a5298&gt;</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>September 04, 2017 12:31:37 +0530</td></tr><tr><th>Params</th><td>#&lt;User:0x000095e402ce78&gt;</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>September 04, 2017 12:41:28 +0530</td></tr><tr><th>Params</th><td>#&lt;User id: 12, email: &quot;tannakartikey@gmail.com&quot;, created_at: &quot;2017-08-05 15:28:27&quot;, updated_at: &quot;2017-09-02 10:55:30&quot;, first_name: nil, last_name: nil, home_port: nil, state_waters: &quot;MA&quot;, vessel_name: nil, subscription_tier: nil, stripe_customer_id: &quot;cus_BJ1cLzc7y1qKmK&quot;, subscription_id: &quot;sub_BKDOt4TEmi0p5y&quot;, is_active: true, payment_source: &quot;src_1AxZHWLl1LzrhllYwM9jyWR7&quot;, deleted_at: nil&gt;</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>September 04, 2017 12:43:13 +0530</td></tr><tr><th>Params</th><td>#&lt;User id: 12, email: &quot;tannakartikey@gmail.com&quot;, created_at: &quot;2017-08-05 15:28:27&quot;, updated_at: &quot;2017-09-02 10:55:30&quot;, first_name: nil, last_name: nil, home_port: nil, state_waters: &quot;MA&quot;, vessel_name: nil, subscription_tier: nil, stripe_customer_id: &quot;cus_BJ1cLzc7y1qKmK&quot;, subscription_id: &quot;sub_BKDOt4TEmi0p5y&quot;, is_active: true, payment_source: &quot;src_1AxZHWLl1LzrhllYwM9jyWR7&quot;, deleted_at: nil&gt;</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>September 04, 2017 12:44:08 +0530</td></tr><tr><th>Params</th><td>#&lt;User id: 12, email: &quot;tannakartikey@gmail.com&quot;, created_at: &quot;2017-08-05 15:28:27&quot;, updated_at: &quot;2017-09-02 10:55:30&quot;, first_name: nil, last_name: nil, home_port: nil, state_waters: &quot;MA&quot;, vessel_name: nil, subscription_tier: nil, stripe_customer_id: &quot;cus_BJ1cLzc7y1qKmK&quot;, subscription_id: &quot;sub_BKDOt4TEmi0p5y&quot;, is_active: true, payment_source: &quot;src_1AxZHWLl1LzrhllYwM9jyWR7&quot;, deleted_at: nil&gt;</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>September 04, 2017 12:44:37 +0530</td></tr><tr><th>Params</th><td>#&lt;User id: 12, email: &quot;tannakartikey@gmail.com&quot;, created_at: &quot;2017-08-05 15:28:27&quot;, updated_at: &quot;2017-09-02 10:55:30&quot;, first_name: nil, last_name: nil, home_port: nil, state_waters: &quot;MA&quot;, vessel_name: nil, subscription_tier: nil, stripe_customer_id: &quot;cus_BJ1cLzc7y1qKmK&quot;, subscription_id: &quot;sub_BKDOt4TEmi0p5y&quot;, is_active: true, payment_source: &quot;src_1AxZHWLl1LzrhllYwM9jyWR7&quot;, deleted_at: nil&gt;</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>September 04, 2017 12:47:12 +0530</td></tr><tr><th>Params</th><td>#&lt;User id: 12, email: &quot;tannakartikey@gmail.com&quot;, created_at: &quot;2017-08-05 15:28:27&quot;, updated_at: &quot;2017-09-02 10:55:30&quot;, first_name: nil, last_name: nil, home_port: nil, state_waters: &quot;MA&quot;, vessel_name: nil, subscription_tier: nil, stripe_customer_id: &quot;cus_BJ1cLzc7y1qKmK&quot;, subscription_id: &quot;sub_BKDOt4TEmi0p5y&quot;, is_active: true, payment_source: &quot;src_1AxZHWLl1LzrhllYwM9jyWR7&quot;, deleted_at: nil&gt;</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>September 04, 2017 12:48:41 +0530</td></tr><tr><th>Params</th><td>#&lt;User id: 12, email: &quot;tannakartikey@gmail.com&quot;, created_at: &quot;2017-08-05 15:28:27&quot;, updated_at: &quot;2017-09-02 10:55:30&quot;, first_name: nil, last_name: nil, home_port: nil, state_waters: &quot;MA&quot;, vessel_name: nil, subscription_tier: nil, stripe_customer_id: &quot;cus_BJ1cLzc7y1qKmK&quot;, subscription_id: &quot;sub_BKDOt4TEmi0p5y&quot;, is_active: true, payment_source: &quot;src_1AxZHWLl1LzrhllYwM9jyWR7&quot;, deleted_at: nil&gt;</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>September 04, 2017 12:49:50 +0530</td></tr><tr><th>Params</th><td>#&lt;User id: 12, email: &quot;tannakartikey@gmail.com&quot;, created_at: &quot;2017-08-05 15:28:27&quot;, updated_at: &quot;2017-09-02 10:55:30&quot;, first_name: nil, last_name: nil, home_port: nil, state_waters: &quot;MA&quot;, vessel_name: nil, subscription_tier: nil, stripe_customer_id: &quot;cus_BJ1cLzc7y1qKmK&quot;, subscription_id: &quot;sub_BKDOt4TEmi0p5y&quot;, is_active: true, payment_source: &quot;src_1AxZHWLl1LzrhllYwM9jyWR7&quot;, deleted_at: nil&gt;</td></tr></table>
