### ISSUE TITLE
#<StripeController:0xXXXXXX>#events (ArgumentError) "invalid date"

### ISSUE THREAD

**Issue by tannakartikey** [tannakartikey/currents#320]
<table><tr><th>Exception</th><td>invalid date</td></tr><tr><th>Last Occurrence</th><td>September 11, 2017 16:08:57 +0530</td></tr><tr><th>Count</th><td>8</td></tr></table>

## Stack Trace
<pre><a href='https://github.com/tannakartikey/currents/blob/c2507397776c529a36cdddfeabf342044851f826/app/controllers/stripe_controller.rb#L61'>[app].../app/controllers/stripe_controller.rb:61:in `strptime'</a>
<a href='https://github.com/tannakartikey/currents/blob/c2507397776c529a36cdddfeabf342044851f826/app/controllers/stripe_controller.rb#L61'>[app].../app/controllers/stripe_controller.rb:61:in `event_process'</a>
<a href='https://github.com/tannakartikey/currents/blob/c2507397776c529a36cdddfeabf342044851f826/app/controllers/stripe_controller.rb#L23'>[app].../app/controllers/stripe_controller.rb:23:in `block in events'</a></pre>
Fingerprint: `5b41bc1fab648f4eda9495c57931889876c7dbbb`

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>September 04, 2017 12:52:33 +0530</td></tr><tr><th>Params</th><td>#&lt;User id: 12, email: &quot;tannakartikey@gmail.com&quot;, created_at: &quot;2017-08-05 15:28:27&quot;, updated_at: &quot;2017-09-02 10:55:30&quot;, first_name: nil, last_name: nil, home_port: nil, state_waters: &quot;MA&quot;, vessel_name: nil, subscription_tier: nil, stripe_customer_id: &quot;cus_BJ1cLzc7y1qKmK&quot;, subscription_id: &quot;sub_BKDOt4TEmi0p5y&quot;, is_active: true, payment_source: &quot;src_1AxZHWLl1LzrhllYwM9jyWR7&quot;, deleted_at: nil&gt;</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>September 04, 2017 12:55:20 +0530</td></tr><tr><th>Params</th><td>#&lt;User id: 12, email: &quot;tannakartikey@gmail.com&quot;, created_at: &quot;2017-08-05 15:28:27&quot;, updated_at: &quot;2017-09-02 10:55:30&quot;, first_name: nil, last_name: nil, home_port: nil, state_waters: &quot;MA&quot;, vessel_name: nil, subscription_tier: nil, stripe_customer_id: &quot;cus_BJ1cLzc7y1qKmK&quot;, subscription_id: &quot;sub_BKDOt4TEmi0p5y&quot;, is_active: true, payment_source: &quot;src_1AxZHWLl1LzrhllYwM9jyWR7&quot;, deleted_at: nil&gt;</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>September 04, 2017 13:02:09 +0530</td></tr><tr><th>Params</th><td>#&lt;User id: 12, email: &quot;tannakartikey@gmail.com&quot;, created_at: &quot;2017-08-05 15:28:27&quot;, updated_at: &quot;2017-09-02 10:55:30&quot;, first_name: nil, last_name: nil, home_port: nil, state_waters: &quot;MA&quot;, vessel_name: nil, subscription_tier: nil, stripe_customer_id: &quot;cus_BJ1cLzc7y1qKmK&quot;, subscription_id: &quot;sub_BKDOt4TEmi0p5y&quot;, is_active: true, payment_source: &quot;src_1AxZHWLl1LzrhllYwM9jyWR7&quot;, deleted_at: nil&gt;</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>September 04, 2017 13:02:09 +0530</td></tr><tr><th>Params</th><td>#&lt;User id: 12, email: &quot;tannakartikey@gmail.com&quot;, created_at: &quot;2017-08-05 15:28:27&quot;, updated_at: &quot;2017-09-02 10:55:30&quot;, first_name: nil, last_name: nil, home_port: nil, state_waters: &quot;MA&quot;, vessel_name: nil, subscription_tier: nil, stripe_customer_id: &quot;cus_BJ1cLzc7y1qKmK&quot;, subscription_id: &quot;sub_BKDOt4TEmi0p5y&quot;, is_active: true, payment_source: &quot;src_1AxZHWLl1LzrhllYwM9jyWR7&quot;, deleted_at: nil&gt;</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>September 04, 2017 13:02:51 +0530</td></tr><tr><th>Params</th><td>#&lt;User id: 12, email: &quot;tannakartikey@gmail.com&quot;, created_at: &quot;2017-08-05 15:28:27&quot;, updated_at: &quot;2017-09-02 10:55:30&quot;, first_name: nil, last_name: nil, home_port: nil, state_waters: &quot;MA&quot;, vessel_name: nil, subscription_tier: nil, stripe_customer_id: &quot;cus_BJ1cLzc7y1qKmK&quot;, subscription_id: &quot;sub_BKDOt4TEmi0p5y&quot;, is_active: true, payment_source: &quot;src_1AxZHWLl1LzrhllYwM9jyWR7&quot;, deleted_at: nil&gt;</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>September 04, 2017 15:19:30 +0530</td></tr><tr><th>Params</th><td>#&lt;User id: 12, email: &quot;tannakartikey@gmail.com&quot;, created_at: &quot;2017-08-05 15:28:27&quot;, updated_at: &quot;2017-09-02 10:55:30&quot;, first_name: nil, last_name: nil, home_port: nil, state_waters: &quot;MA&quot;, vessel_name: nil, subscription_tier: nil, stripe_customer_id: &quot;cus_BJ1cLzc7y1qKmK&quot;, subscription_id: &quot;sub_BKDOt4TEmi0p5y&quot;, is_active: true, payment_source: &quot;src_1AxZHWLl1LzrhllYwM9jyWR7&quot;, deleted_at: nil&gt;</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>September 04, 2017 15:21:48 +0530</td></tr><tr><th>Params</th><td>#&lt;User id: 12, email: &quot;tannakartikey@gmail.com&quot;, created_at: &quot;2017-08-05 15:28:27&quot;, updated_at: &quot;2017-09-02 10:55:30&quot;, first_name: nil, last_name: nil, home_port: nil, state_waters: &quot;MA&quot;, vessel_name: nil, subscription_tier: nil, stripe_customer_id: &quot;cus_BJ1cLzc7y1qKmK&quot;, subscription_id: &quot;sub_BKDOt4TEmi0p5y&quot;, is_active: true, payment_source: &quot;src_1AxZHWLl1LzrhllYwM9jyWR7&quot;, deleted_at: nil&gt;</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>September 11, 2017 16:07:59 +0530</td></tr><tr><th>Params</th><td>#&lt;User id: 59, email: &quot;margaret.shields@kessler.com&quot;, created_at: &quot;2017-09-07 14:10:38&quot;, updated_at: &quot;2017-09-08 14:23:53&quot;, first_name: nil, last_name: nil, home_port: nil, state_waters: &quot;MA&quot;, vessel_name: nil, subscription_tier: nil, stripe_customer_id: &quot;cus_BM90KDKPzhC2EJ&quot;, subscription_id: &quot;sub_BM9BJ7IZJCCaqo&quot;, is_active: false, payment_source: nil, deleted_at: nil&gt;</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>September 11, 2017 16:08:57 +0530</td></tr><tr><th>Params</th><td>#&lt;User id: 59, email: &quot;margaret.shields@kessler.com&quot;, created_at: &quot;2017-09-07 14:10:38&quot;, updated_at: &quot;2017-09-08 14:23:53&quot;, first_name: nil, last_name: nil, home_port: nil, state_waters: &quot;MA&quot;, vessel_name: nil, subscription_tier: nil, stripe_customer_id: &quot;cus_BM90KDKPzhC2EJ&quot;, subscription_id: &quot;sub_BM9BJ7IZJCCaqo&quot;, is_active: false, payment_source: nil, deleted_at: nil&gt;</td></tr></table>
