### ISSUE TITLE
#<StripeController:0xXXXXXX>#events (NoMethodError) "undefined method `last4' for nil:NilClass"

### ISSUE THREAD

**Issue by tannakartikey** [tannakartikey/currents#321]
<table><tr><th>Exception</th><td>undefined method `last4&#39; for nil:NilClass</td></tr><tr><th>Last Occurrence</th><td>September 04, 2017 18:58:36 +0530</td></tr><tr><th>Count</th><td>2</td></tr></table>

## Stack Trace
<pre><a href='https://github.com/tannakartikey/currents/blob/c2507397776c529a36cdddfeabf342044851f826/app/controllers/stripe_controller.rb#L95'>[app].../app/controllers/stripe_controller.rb:95:in `event_process'</a>
<a href='https://github.com/tannakartikey/currents/blob/c2507397776c529a36cdddfeabf342044851f826/app/controllers/stripe_controller.rb#L23'>[app].../app/controllers/stripe_controller.rb:23:in `block in events'</a></pre>
Fingerprint: `968b8bad870566f448e53e2d1479a59118d41784`

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>September 04, 2017 18:57:27 +0530</td></tr><tr><th>Params</th><td>#&lt;User id: 12, email: &quot;tannakartikey@gmail.com&quot;, created_at: &quot;2017-08-05 15:28:27&quot;, updated_at: &quot;2017-09-04 10:25:27&quot;, first_name: nil, last_name: nil, home_port: nil, state_waters: &quot;MA&quot;, vessel_name: nil, subscription_tier: nil, stripe_customer_id: &quot;cus_BJ1cLzc7y1qKmK&quot;, subscription_id: &quot;sub_BKDOt4TEmi0p5y&quot;, is_active: true, payment_source: &quot;src_1AyHlcLl1LzrhllYLka2gQwk&quot;, deleted_at: nil&gt;</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>September 04, 2017 18:58:36 +0530</td></tr><tr><th>Params</th><td>#&lt;User id: 12, email: &quot;tannakartikey@gmail.com&quot;, created_at: &quot;2017-08-05 15:28:27&quot;, updated_at: &quot;2017-09-04 10:25:27&quot;, first_name: nil, last_name: nil, home_port: nil, state_waters: &quot;MA&quot;, vessel_name: nil, subscription_tier: nil, stripe_customer_id: &quot;cus_BJ1cLzc7y1qKmK&quot;, subscription_id: &quot;sub_BKDOt4TEmi0p5y&quot;, is_active: true, payment_source: &quot;src_1AyHlcLl1LzrhllYLka2gQwk&quot;, deleted_at: nil&gt;</td></tr></table>
