### ISSUE TITLE
# (Stripe::InvalidRequestError) "No such source: src_1AzQOZLl1LzrhllY5PnoRNOz"

### ISSUE THREAD

**Issue by tannakartikey** [tannakartikey/currents#325]
<table><tr><th>Exception</th><td>(Status 404) (Request req_YlzjMPo6k7Wfyr) No such source: src_1AzQOZLl1LzrhllY5PnoRNOz</td></tr><tr><th>Last Occurrence</th><td>September 07, 2017 19:28:32 +0530</td></tr><tr><th>Count</th><td>1</td></tr></table>

## Stack Trace
<pre>[bundle].../gems/stripe-3.0.0/lib/stripe/stripe_client.rb:253:in `handle_error_response'
[bundle].../gems/stripe-3.0.0/lib/stripe/stripe_client.rb:200:in `rescue in execute_request_with_rescues'
[bundle].../gems/stripe-3.0.0/lib/stripe/stripe_client.rb:184:in `execute_request_with_rescues'
[bundle].../gems/stripe-3.0.0/lib/stripe/stripe_client.rb:136:in `execute_request'
[bundle].../gems/stripe-3.0.0/lib/stripe/api_operations/request.rb:19:in `request'
[bundle].../gems/stripe-3.0.0/lib/stripe/api_operations/request.rb:58:in `request'
[bundle].../gems/stripe-3.0.0/lib/stripe/source.rb:11:in `delete'
<a href='https://github.com/tannakartikey/currents/blob/809d3b2508350d866735ef6757f1e9366ba5c216/app/models/stripe_customer.rb#L24'>[app].../app/models/stripe_customer.rb:24:in `block in delete_all_sources'</a>
[bundle].../gems/stripe-3.0.0/lib/stripe/list_object.rb:42:in `each'
[bundle].../gems/stripe-3.0.0/lib/stripe/list_object.rb:42:in `each'
<a href='https://github.com/tannakartikey/currents/blob/809d3b2508350d866735ef6757f1e9366ba5c216/app/models/stripe_customer.rb#L23'>[app].../app/models/stripe_customer.rb:23:in `delete_all_sources'</a>
<a href='https://github.com/tannakartikey/currents/blob/809d3b2508350d866735ef6757f1e9366ba5c216/app/models/exception_wrapper.rb#L11'>[app].../app/models/exception_wrapper.rb:11:in `call'</a>
<a href='https://github.com/tannakartikey/currents/blob/809d3b2508350d866735ef6757f1e9366ba5c216/app/models/exception_wrapper.rb#L11'>[app].../app/models/exception_wrapper.rb:11:in `block (2 levels) in singleton class'</a>
<a href='https://github.com/tannakartikey/currents/blob/809d3b2508350d866735ef6757f1e9366ba5c216/app/controllers/stripe_controller.rb#L45'>[app].../app/controllers/stripe_controller.rb:45:in `event_process'</a>
<a href='https://github.com/tannakartikey/currents/blob/809d3b2508350d866735ef6757f1e9366ba5c216/app/controllers/stripe_controller.rb#L23'>[app].../app/controllers/stripe_controller.rb:23:in `block in events'</a></pre>
Fingerprint: `a15a92792463c45c8104d8ec897407d12e544b6f`

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>September 07, 2017 19:28:32 +0530</td></tr><tr><th>Params</th><td>#&lt;User id: 12, email: &quot;tannakartikey@gmail.com&quot;, created_at: &quot;2017-08-05 15:28:27&quot;, updated_at: &quot;2017-09-07 13:58:20&quot;, first_name: nil, last_name: nil, home_port: nil, state_waters: &quot;MA&quot;, vessel_name: nil, subscription_tier: nil, stripe_customer_id: &quot;cus_BJ1cLzc7y1qKmK&quot;, subscription_id: nil, is_active: false, payment_source: &quot;src_1AzQOZLl1LzrhllY5PnoRNOz&quot;, deleted_at: nil&gt;</td></tr></table>
