### ISSUE TITLE
#<StripeController:0xXXXXXX>#events (NoMethodError) "undefined method `attempt_count' for nil:NilClass"

### ISSUE THREAD

**Issue by tannakartikey** [tannakartikey/currents#327]
<table><tr><th>Exception</th><td>undefined method `attempt_count&#39; for nil:NilClass</td></tr><tr><th>Last Occurrence</th><td>October 05, 2017 08:42:31 +0530</td></tr><tr><th>Count</th><td>19</td></tr></table>

## Stack Trace
<pre><a href='https://github.com/tannakartikey/currents/blob/809d3b2508350d866735ef6757f1e9366ba5c216/app/controllers/stripe_controller.rb#L72'>[app].../app/controllers/stripe_controller.rb:72:in `event_process'</a>
<a href='https://github.com/tannakartikey/currents/blob/809d3b2508350d866735ef6757f1e9366ba5c216/app/controllers/stripe_controller.rb#L23'>[app].../app/controllers/stripe_controller.rb:23:in `block in events'</a></pre>
Fingerprint: `0ae71275372713ee1a73470192e5640dad4a7fac`

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>September 07, 2017 19:46:25 +0530</td></tr><tr><th>Params</th><td>#&lt;User id: 59, email: &quot;margaret.shields@kessler.com&quot;, created_at: &quot;2017-09-07 14:10:38&quot;, updated_at: &quot;2017-09-07 14:16:02&quot;, first_name: nil, last_name: nil, home_port: nil, state_waters: &quot;MA&quot;, vessel_name: nil, subscription_tier: nil, stripe_customer_id: &quot;cus_BM90KDKPzhC2EJ&quot;, subscription_id: nil, is_active: false, payment_source: nil, deleted_at: nil&gt;</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>September 07, 2017 20:37:08 +0530</td></tr><tr><th>Params</th><td>#&lt;User id: 12, email: &quot;tannakartikey@gmail.com&quot;, created_at: &quot;2017-08-05 15:28:27&quot;, updated_at: &quot;2017-09-07 14:00:24&quot;, first_name: nil, last_name: nil, home_port: nil, state_waters: &quot;MA&quot;, vessel_name: nil, subscription_tier: nil, stripe_customer_id: &quot;cus_BJ1cLzc7y1qKmK&quot;, subscription_id: &quot;sub_BM8pEIICmWHGh9&quot;, is_active: true, payment_source: &quot;src_1AzQYKLl1LzrhllYCPePSe6K&quot;, deleted_at: nil&gt;</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>September 07, 2017 20:37:09 +0530</td></tr><tr><th>Params</th><td>#&lt;User id: 12, email: &quot;tannakartikey@gmail.com&quot;, created_at: &quot;2017-08-05 15:28:27&quot;, updated_at: &quot;2017-09-07 14:00:24&quot;, first_name: nil, last_name: nil, home_port: nil, state_waters: &quot;MA&quot;, vessel_name: nil, subscription_tier: nil, stripe_customer_id: &quot;cus_BJ1cLzc7y1qKmK&quot;, subscription_id: &quot;sub_BM8pEIICmWHGh9&quot;, is_active: true, payment_source: &quot;src_1AzQYKLl1LzrhllYCPePSe6K&quot;, deleted_at: nil&gt;</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>September 07, 2017 20:42:16 +0530</td></tr><tr><th>Params</th><td>#&lt;User id: 56, email: &quot;tony.jewess@purdy.name&quot;, created_at: &quot;2017-09-07 14:04:52&quot;, updated_at: &quot;2017-09-07 14:11:28&quot;, first_name: nil, last_name: nil, home_port: nil, state_waters: &quot;MA&quot;, vessel_name: nil, subscription_tier: nil, stripe_customer_id: &quot;cus_BM8utInSAFSKrl&quot;, subscription_id: &quot;sub_BM8umxQ5yHsIA7&quot;, is_active: false, payment_source: nil, deleted_at: nil&gt;</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>September 07, 2017 20:42:21 +0530</td></tr><tr><th>Params</th><td>#&lt;User id: 56, email: &quot;tony.jewess@purdy.name&quot;, created_at: &quot;2017-09-07 14:04:52&quot;, updated_at: &quot;2017-09-07 14:11:28&quot;, first_name: nil, last_name: nil, home_port: nil, state_waters: &quot;MA&quot;, vessel_name: nil, subscription_tier: nil, stripe_customer_id: &quot;cus_BM8utInSAFSKrl&quot;, subscription_id: &quot;sub_BM8umxQ5yHsIA7&quot;, is_active: false, payment_source: nil, deleted_at: nil&gt;</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>September 07, 2017 20:43:49 +0530</td></tr><tr><th>Params</th><td>#&lt;User id: 57, email: &quot;eleonor@luettgen.us&quot;, created_at: &quot;2017-09-07 14:06:14&quot;, updated_at: &quot;2017-09-07 14:13:40&quot;, first_name: nil, last_name: nil, home_port: nil, state_waters: &quot;MA&quot;, vessel_name: nil, subscription_tier: nil, stripe_customer_id: &quot;cus_BM8vWvyhPx5bNb&quot;, subscription_id: &quot;sub_BM8vI25Ce1AWD9&quot;, is_active: false, payment_source: nil, deleted_at: nil&gt;</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>September 07, 2017 20:43:50 +0530</td></tr><tr><th>Params</th><td>#&lt;User id: 57, email: &quot;eleonor@luettgen.us&quot;, created_at: &quot;2017-09-07 14:06:14&quot;, updated_at: &quot;2017-09-07 14:13:40&quot;, first_name: nil, last_name: nil, home_port: nil, state_waters: &quot;MA&quot;, vessel_name: nil, subscription_tier: nil, stripe_customer_id: &quot;cus_BM8vWvyhPx5bNb&quot;, subscription_id: &quot;sub_BM8vI25Ce1AWD9&quot;, is_active: false, payment_source: nil, deleted_at: nil&gt;</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>September 07, 2017 20:46:13 +0530</td></tr><tr><th>Params</th><td>#&lt;User id: 58, email: &quot;deeann_olson@christiansenhoeger.name&quot;, created_at: &quot;2017-09-07 14:08:36&quot;, updated_at: &quot;2017-09-07 14:15:47&quot;, first_name: nil, last_name: nil, home_port: nil, state_waters: &quot;MA&quot;, vessel_name: nil, subscription_tier: nil, stripe_customer_id: &quot;cus_BM8y6cWGysGvkP&quot;, subscription_id: &quot;sub_BM8yYNM649hPuZ&quot;, is_active: false, payment_source: nil, deleted_at: nil&gt;</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>September 07, 2017 20:46:16 +0530</td></tr><tr><th>Params</th><td>#&lt;User id: 58, email: &quot;deeann_olson@christiansenhoeger.name&quot;, created_at: &quot;2017-09-07 14:08:36&quot;, updated_at: &quot;2017-09-07 14:15:47&quot;, first_name: nil, last_name: nil, home_port: nil, state_waters: &quot;MA&quot;, vessel_name: nil, subscription_tier: nil, stripe_customer_id: &quot;cus_BM8y6cWGysGvkP&quot;, subscription_id: &quot;sub_BM8yYNM649hPuZ&quot;, is_active: false, payment_source: nil, deleted_at: nil&gt;</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>September 08, 2017 20:54:31 +0530</td></tr><tr><th>Params</th><td>#&lt;User id: 59, email: &quot;margaret.shields@kessler.com&quot;, created_at: &quot;2017-09-07 14:10:38&quot;, updated_at: &quot;2017-09-08 14:23:53&quot;, first_name: nil, last_name: nil, home_port: nil, state_waters: &quot;MA&quot;, vessel_name: nil, subscription_tier: nil, stripe_customer_id: &quot;cus_BM90KDKPzhC2EJ&quot;, subscription_id: &quot;sub_BM9BJ7IZJCCaqo&quot;, is_active: false, payment_source: nil, deleted_at: nil&gt;</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>September 11, 2017 10:28:34 +0530</td></tr><tr><th>Params</th><td>#&lt;User id: 59, email: &quot;margaret.shields@kessler.com&quot;, created_at: &quot;2017-09-07 14:10:38&quot;, updated_at: &quot;2017-09-08 14:23:53&quot;, first_name: nil, last_name: nil, home_port: nil, state_waters: &quot;MA&quot;, vessel_name: nil, subscription_tier: nil, stripe_customer_id: &quot;cus_BM90KDKPzhC2EJ&quot;, subscription_id: &quot;sub_BM9BJ7IZJCCaqo&quot;, is_active: false, payment_source: nil, deleted_at: nil&gt;</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>September 12, 2017 20:54:35 +0530</td></tr><tr><th>Params</th><td>#&lt;User id: 59, email: &quot;margaret.shields@kessler.com&quot;, created_at: &quot;2017-09-07 14:10:38&quot;, updated_at: &quot;2017-09-08 14:23:53&quot;, first_name: nil, last_name: nil, home_port: nil, state_waters: &quot;MA&quot;, vessel_name: nil, subscription_tier: nil, stripe_customer_id: &quot;cus_BM90KDKPzhC2EJ&quot;, subscription_id: &quot;sub_BM9BJ7IZJCCaqo&quot;, is_active: false, payment_source: nil, deleted_at: nil&gt;</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>September 12, 2017 20:54:38 +0530</td></tr><tr><th>Params</th><td>#&lt;User id: 59, email: &quot;margaret.shields@kessler.com&quot;, created_at: &quot;2017-09-07 14:10:38&quot;, updated_at: &quot;2017-09-08 14:23:53&quot;, first_name: nil, last_name: nil, home_port: nil, state_waters: &quot;MA&quot;, vessel_name: nil, subscription_tier: nil, stripe_customer_id: &quot;cus_BM90KDKPzhC2EJ&quot;, subscription_id: &quot;sub_BM9BJ7IZJCCaqo&quot;, is_active: false, payment_source: nil, deleted_at: nil&gt;</td></tr></table>
