### ISSUE TITLE
#<StripeController:0xXXXXXX>#events (NoMethodError) "undefined method `includes?' for #<Array:0xXXXXXX>
Did you mean?  include?"

### ISSUE THREAD

**Issue by tannakartikey** [tannakartikey/currents#330]
<table><tr><th>Exception</th><td>undefined method `includes?&#39; for #&lt;Array:0x00007f6af4f788&gt;
Did you mean?  include?</td></tr><tr><th>Last Occurrence</th><td>September 07, 2017 20:02:06 +0530</td></tr><tr><th>Count</th><td>2</td></tr></table>

## Stack Trace
<pre><a href='https://github.com/tannakartikey/currents/blob/809d3b2508350d866735ef6757f1e9366ba5c216/app/controllers/stripe_controller.rb#L102'>[app].../app/controllers/stripe_controller.rb:102:in `event_process'</a>
<a href='https://github.com/tannakartikey/currents/blob/809d3b2508350d866735ef6757f1e9366ba5c216/app/controllers/stripe_controller.rb#L23'>[app].../app/controllers/stripe_controller.rb:23:in `block in events'</a></pre>
Fingerprint: `9c8b4f99bfe6352b8ee5bbfb777fbcc8b007bf53`

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>September 07, 2017 20:01:53 +0530</td></tr><tr><th>Params</th><td>#&lt;User id: 59, email: &quot;margaret.shields@kessler.com&quot;, created_at: &quot;2017-09-07 14:10:38&quot;, updated_at: &quot;2017-09-07 14:21:47&quot;, first_name: nil, last_name: nil, home_port: nil, state_waters: &quot;MA&quot;, vessel_name: nil, subscription_tier: nil, stripe_customer_id: &quot;cus_BM90KDKPzhC2EJ&quot;, subscription_id: &quot;sub_BM9BJ7IZJCCaqo&quot;, is_active: true, payment_source: nil, deleted_at: nil&gt;</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>September 07, 2017 20:02:06 +0530</td></tr><tr><th>Params</th><td>#&lt;User id: 59, email: &quot;margaret.shields@kessler.com&quot;, created_at: &quot;2017-09-07 14:10:38&quot;, updated_at: &quot;2017-09-07 14:21:47&quot;, first_name: nil, last_name: nil, home_port: nil, state_waters: &quot;MA&quot;, vessel_name: nil, subscription_tier: nil, stripe_customer_id: &quot;cus_BM90KDKPzhC2EJ&quot;, subscription_id: &quot;sub_BM9BJ7IZJCCaqo&quot;, is_active: true, payment_source: nil, deleted_at: nil&gt;</td></tr></table>
