### ISSUE TITLE
# (ArgumentError) "wrong number of arguments (given 0, expected 1..2)"

### ISSUE THREAD

**Issue by tannakartikey** [tannakartikey/currents#331]
<table><tr><th>Exception</th><td>wrong number of arguments (given 0, expected 1..2)</td></tr><tr><th>Last Occurrence</th><td>September 11, 2017 05:16:55 +0000</td></tr><tr><th>Count</th><td>1</td></tr></table>

## Stack Trace
<pre><a href='https://github.com/tannakartikey/currents/blob/809d3b2508350d866735ef6757f1e9366ba5c216/app/models/stripe_subscription.rb#L2'>[app].../app/models/stripe_subscription.rb:2:in `create'</a>
<a href='https://github.com/tannakartikey/currents/blob/809d3b2508350d866735ef6757f1e9366ba5c216/app/models/exception_wrapper.rb#L11'>[app].../app/models/exception_wrapper.rb:11:in `call'</a>
<a href='https://github.com/tannakartikey/currents/blob/809d3b2508350d866735ef6757f1e9366ba5c216/app/models/exception_wrapper.rb#L11'>[app].../app/models/exception_wrapper.rb:11:in `block (2 levels) in singleton class'</a>
(irb):15:in `irb_binding'
<a href='https://github.com/tannakartikey/currents/blob/809d3b2508350d866735ef6757f1e9366ba5c216/vendor/ruby-2.3.4/lib/ruby/2.3.0/irb/workspace.rb#L87'>[app].../vendor/ruby-2.3.4/lib/ruby/2.3.0/irb/workspace.rb:87:in `eval'</a>
<a href='https://github.com/tannakartikey/currents/blob/809d3b2508350d866735ef6757f1e9366ba5c216/vendor/ruby-2.3.4/lib/ruby/2.3.0/irb/workspace.rb#L87'>[app].../vendor/ruby-2.3.4/lib/ruby/2.3.0/irb/workspace.rb:87:in `evaluate'</a>
<a href='https://github.com/tannakartikey/currents/blob/809d3b2508350d866735ef6757f1e9366ba5c216/vendor/ruby-2.3.4/lib/ruby/2.3.0/irb/context.rb#L380'>[app].../vendor/ruby-2.3.4/lib/ruby/2.3.0/irb/context.rb:380:in `evaluate'</a>
<a href='https://github.com/tannakartikey/currents/blob/809d3b2508350d866735ef6757f1e9366ba5c216/vendor/ruby-2.3.4/lib/ruby/2.3.0/irb.rb#L489'>[app].../vendor/ruby-2.3.4/lib/ruby/2.3.0/irb.rb:489:in `block (2 levels) in eval_input'</a>
<a href='https://github.com/tannakartikey/currents/blob/809d3b2508350d866735ef6757f1e9366ba5c216/vendor/ruby-2.3.4/lib/ruby/2.3.0/irb.rb#L623'>[app].../vendor/ruby-2.3.4/lib/ruby/2.3.0/irb.rb:623:in `signal_status'</a>
<a href='https://github.com/tannakartikey/currents/blob/809d3b2508350d866735ef6757f1e9366ba5c216/vendor/ruby-2.3.4/lib/ruby/2.3.0/irb.rb#L486'>[app].../vendor/ruby-2.3.4/lib/ruby/2.3.0/irb.rb:486:in `block in eval_input'</a>
<a href='https://github.com/tannakartikey/currents/blob/809d3b2508350d866735ef6757f1e9366ba5c216/vendor/ruby-2.3.4/lib/ruby/2.3.0/irb/ruby-lex.rb#L246'>[app].../vendor/ruby-2.3.4/lib/ruby/2.3.0/irb/ruby-lex.rb:246:in `block (2 levels) in each_top_level_statement'</a>
<a href='https://github.com/tannakartikey/currents/blob/809d3b2508350d866735ef6757f1e9366ba5c216/vendor/ruby-2.3.4/lib/ruby/2.3.0/irb/ruby-lex.rb#L232'>[app].../vendor/ruby-2.3.4/lib/ruby/2.3.0/irb/ruby-lex.rb:232:in `loop'</a>
<a href='https://github.com/tannakartikey/currents/blob/809d3b2508350d866735ef6757f1e9366ba5c216/vendor/ruby-2.3.4/lib/ruby/2.3.0/irb/ruby-lex.rb#L232'>[app].../vendor/ruby-2.3.4/lib/ruby/2.3.0/irb/ruby-lex.rb:232:in `block in each_top_level_statement'</a>
<a href='https://github.com/tannakartikey/currents/blob/809d3b2508350d866735ef6757f1e9366ba5c216/vendor/ruby-2.3.4/lib/ruby/2.3.0/irb/ruby-lex.rb#L231'>[app].../vendor/ruby-2.3.4/lib/ruby/2.3.0/irb/ruby-lex.rb:231:in `catch'</a>
<a href='https://github.com/tannakartikey/currents/blob/809d3b2508350d866735ef6757f1e9366ba5c216/vendor/ruby-2.3.4/lib/ruby/2.3.0/irb/ruby-lex.rb#L231'>[app].../vendor/ruby-2.3.4/lib/ruby/2.3.0/irb/ruby-lex.rb:231:in `each_top_level_statement'</a>
<a href='https://github.com/tannakartikey/currents/blob/809d3b2508350d866735ef6757f1e9366ba5c216/vendor/ruby-2.3.4/lib/ruby/2.3.0/irb.rb#L485'>[app].../vendor/ruby-2.3.4/lib/ruby/2.3.0/irb.rb:485:in `eval_input'</a>
<a href='https://github.com/tannakartikey/currents/blob/809d3b2508350d866735ef6757f1e9366ba5c216/vendor/ruby-2.3.4/lib/ruby/2.3.0/irb.rb#L395'>[app].../vendor/ruby-2.3.4/lib/ruby/2.3.0/irb.rb:395:in `block in start'</a>
<a href='https://github.com/tannakartikey/currents/blob/809d3b2508350d866735ef6757f1e9366ba5c216/vendor/ruby-2.3.4/lib/ruby/2.3.0/irb.rb#L394'>[app].../vendor/ruby-2.3.4/lib/ruby/2.3.0/irb.rb:394:in `catch'</a>
<a href='https://github.com/tannakartikey/currents/blob/809d3b2508350d866735ef6757f1e9366ba5c216/vendor/ruby-2.3.4/lib/ruby/2.3.0/irb.rb#L394'>[app].../vendor/ruby-2.3.4/lib/ruby/2.3.0/irb.rb:394:in `start'</a>
[bundle].../gems/railties-4.2.7.1/lib/rails/commands/console.rb:110:in `start'
[bundle].../gems/railties-4.2.7.1/lib/rails/commands/console.rb:9:in `start'
[bundle].../gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:68:in `console'
[bundle].../gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
[bundle].../gems/railties-4.2.7.1/lib/rails/commands.rb:17:in `<top (required)>'
<a href='https://github.com/tannakartikey/currents/blob/809d3b2508350d866735ef6757f1e9366ba5c216/bin/rails#L9'>[app].../bin/rails:9:in `require'</a>
<a href='https://github.com/tannakartikey/currents/blob/809d3b2508350d866735ef6757f1e9366ba5c216/bin/rails#L9'>[app].../bin/rails:9:in `<main>'</a></pre>
Fingerprint: `cead8cf55dadb3833c746416a351c64a3f066908`

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>September 11, 2017 05:16:55 +0000</td></tr><tr><th>Params</th><td>nil</td></tr></table>
