### ISSUE TITLE
# (Stripe::InvalidRequestError) "Invalid integer"

### ISSUE THREAD

**Issue by tannakartikey** [tannakartikey/currents#333]
<table><tr><th>Exception</th><td>(Status 400) (Request req_EhIeanfKUaFlqS) Invalid integer</td></tr><tr><th>Last Occurrence</th><td>September 11, 2017 05:21:06 +0000</td></tr><tr><th>Count</th><td>1</td></tr></table>

## Stack Trace
<pre>[bundle].../gems/stripe-3.3.1/lib/stripe/stripe_client.rb:278:in `handle_error_response'
[bundle].../gems/stripe-3.3.1/lib/stripe/stripe_client.rb:226:in `rescue in execute_request_with_rescues'
[bundle].../gems/stripe-3.3.1/lib/stripe/stripe_client.rb:194:in `execute_request_with_rescues'
[bundle].../gems/stripe-3.3.1/lib/stripe/stripe_client.rb:151:in `execute_request'
[bundle].../gems/stripe-3.3.1/lib/stripe/api_operations/request.rb:19:in `request'
[bundle].../gems/stripe-3.3.1/lib/stripe/api_operations/create.rb:5:in `create'
[bundle].../gems/stripe-3.3.1/lib/stripe/subscription.rb:24:in `create'
<a href='https://github.com/tannakartikey/currents/blob/809d3b2508350d866735ef6757f1e9366ba5c216/app/models/stripe_subscription.rb#L3'>[app].../app/models/stripe_subscription.rb:3:in `create'</a>
<a href='https://github.com/tannakartikey/currents/blob/809d3b2508350d866735ef6757f1e9366ba5c216/app/models/exception_wrapper.rb#L11'>[app].../app/models/exception_wrapper.rb:11:in `call'</a>
<a href='https://github.com/tannakartikey/currents/blob/809d3b2508350d866735ef6757f1e9366ba5c216/app/models/exception_wrapper.rb#L11'>[app].../app/models/exception_wrapper.rb:11:in `block (2 levels) in singleton class'</a>
(irb):17:in `irb_binding'
<a href='https://github.com/tannakartikey/currents/blob/809d3b2508350d866735ef6757f1e9366ba5c216/vendor/ruby-2.3.4/lib/ruby/2.3.0/irb/workspace.rb#L87'>[app].../vendor/ruby-2.3.4/lib/ruby/2.3.0/irb/workspace.rb:87:in `eval'</a>
<a href='https://github.com/tannakartikey/currents/blob/809d3b2508350d866735ef6757f1e9366ba5c216/vendor/ruby-2.3.4/lib/ruby/2.3.0/irb/workspace.rb#L87'>[app].../vendor/ruby-2.3.4/lib/ruby/2.3.0/irb/workspace.rb:87:in `evaluate'</a>
<a href='https://github.com/tannakartikey/currents/blob/809d3b2508350d866735ef6757f1e9366ba5c216/vendor/ruby-2.3.4/lib/ruby/2.3.0/irb/context.rb#L380'>[app].../vendor/ruby-2.3.4/lib/ruby/2.3.0/irb/context.rb:380:in `evaluate'</a>
<a href='https://github.com/tannakartikey/currents/blob/809d3b2508350d866735ef6757f1e9366ba5c216/vendor/ruby-2.3.4/lib/ruby/2.3.0/irb.rb#L489'>[app].../vendor/ruby-2.3.4/lib/ruby/2.3.0/irb.rb:489:in `block (2 levels) in eval_input'</a>
<a href='https://github.com/tannakartikey/currents/blob/809d3b2508350d866735ef6757f1e9366ba5c216/vendor/ruby-2.3.4/lib/ruby/2.3.0/irb.rb#L623'>[app].../vendor/ruby-2.3.4/lib/ruby/2.3.0/irb.rb:623:in `signal_status'</a>
<a href='https://github.com/tannakartikey/currents/blob/809d3b2508350d866735ef6757f1e9366ba5c216/vendor/ruby-2.3.4/lib/ruby/2.3.0/irb.rb#L486'>[app].../vendor/ruby-2.3.4/lib/ruby/2.3.0/irb.rb:486:in `block in eval_input'</a>
<a href='https://github.com/tannakartikey/currents/blob/809d3b2508350d866735ef6757f1e9366ba5c216/vendor/ruby-2.3.4/lib/ruby/2.3.0/irb/ruby-lex.rb#L246'>[app].../vendor/ruby-2.3.4/lib/ruby/2.3.0/irb/ruby-lex.rb:246:in `block (2 levels) in each_top_level_statement'</a>
<a href='https://github.com/tannakartikey/currents/blob/809d3b2508350d866735ef6757f1e9366ba5c216/vendor/ruby-2.3.4/lib/ruby/2.3.0/irb/ruby-lex.rb#L232'>[app].../vendor/ruby-2.3.4/lib/ruby/2.3.0/irb/ruby-lex.rb:232:in `loop'</a>
<a href='https://github.com/tannakartikey/currents/blob/809d3b2508350d866735ef6757f1e9366ba5c216/vendor/ruby-2.3.4/lib/ruby/2.3.0/irb/ruby-lex.rb#L232'>[app].../vendor/ruby-2.3.4/lib/ruby/2.3.0/irb/ruby-lex.rb:232:in `block in each_top_level_statement'</a>
<a href='https://github.com/tannakartikey/currents/blob/809d3b2508350d866735ef6757f1e9366ba5c216/vendor/ruby-2.3.4/lib/ruby/2.3.0/irb/ruby-lex.rb#L231'>[app].../vendor/ruby-2.3.4/lib/ruby/2.3.0/irb/ruby-lex.rb:231:in `catch'</a>
<a href='https://github.com/tannakartikey/currents/blob/809d3b2508350d866735ef6757f1e9366ba5c216/vendor/ruby-2.3.4/lib/ruby/2.3.0/irb/ruby-lex.rb#L231'>[app].../vendor/ruby-2.3.4/lib/ruby/2.3.0/irb/ruby-lex.rb:231:in `each_top_level_statement'</a>
<a href='https://github.com/tannakartikey/currents/blob/809d3b2508350d866735ef6757f1e9366ba5c216/vendor/ruby-2.3.4/lib/ruby/2.3.0/irb.rb#L485'>[app].../vendor/ruby-2.3.4/lib/ruby/2.3.0/irb.rb:485:in `eval_input'</a>
<a href='https://github.com/tannakartikey/currents/blob/809d3b2508350d866735ef6757f1e9366ba5c216/vendor/ruby-2.3.4/lib/ruby/2.3.0/irb.rb#L395'>[app].../vendor/ruby-2.3.4/lib/ruby/2.3.0/irb.rb:395:in `block in start'</a>
<a href='https://github.com/tannakartikey/currents/blob/809d3b2508350d866735ef6757f1e9366ba5c216/vendor/ruby-2.3.4/lib/ruby/2.3.0/irb.rb#L394'>[app].../vendor/ruby-2.3.4/lib/ruby/2.3.0/irb.rb:394:in `catch'</a>
<a href='https://github.com/tannakartikey/currents/blob/809d3b2508350d866735ef6757f1e9366ba5c216/vendor/ruby-2.3.4/lib/ruby/2.3.0/irb.rb#L394'>[app].../vendor/ruby-2.3.4/lib/ruby/2.3.0/irb.rb:394:in `start'</a>
[bundle].../gems/railties-4.2.7.1/lib/rails/commands/console.rb:110:in `start'
[bundle].../gems/railties-4.2.7.1/lib/rails/commands/console.rb:9:in `start'
[bundle].../gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:68:in `console'
[bundle].../gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
[bundle].../gems/railties-4.2.7.1/lib/rails/commands.rb:17:in `<top (required)>'
<a href='https://github.com/tannakartikey/currents/blob/809d3b2508350d866735ef6757f1e9366ba5c216/bin/rails#L9'>[app].../bin/rails:9:in `require'</a>
<a href='https://github.com/tannakartikey/currents/blob/809d3b2508350d866735ef6757f1e9366ba5c216/bin/rails#L9'>[app].../bin/rails:9:in `<main>'</a></pre>
Fingerprint: `bd8c98482215dad4c4795fd8c0f7b92be3a13653`

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>September 11, 2017 05:21:06 +0000</td></tr><tr><th>Params</th><td>#&lt;User id: 4, email: &quot;tannakartikey@gmail.com&quot;, created_at: &quot;2017-07-08 08:57:30&quot;, updated_at: &quot;2017-09-11 05:15:08&quot;, first_name: &quot;Kartikey&quot;, last_name: &quot;Tanna&quot;, home_port: &quot;&quot;, state_waters: &quot;CT&quot;, vessel_name: &quot;&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_BNVFg1D9JuGkfz&quot;, subscription_id: &quot;sub_BHXLM5gZfHACO4&quot;, is_active: true, payment_source: nil, deleted_at: nil&gt;</td></tr></table>
