### ISSUE TITLE
#<StripeController:0xXXXXXX>#events (TypeError) "no implicit conversion of Class into String"

### ISSUE THREAD

**Issue by tannakartikey** [tannakartikey/currents#334]
<table><tr><th>Exception</th><td>no implicit conversion of Class into String</td></tr><tr><th>Last Occurrence</th><td>September 11, 2017 16:07:12 +0530</td></tr><tr><th>Count</th><td>1</td></tr></table>

## Stack Trace
<pre><a href='https://github.com/tannakartikey/currents/blob/809d3b2508350d866735ef6757f1e9366ba5c216/app/controllers/stripe_controller.rb#L84'>[app].../app/controllers/stripe_controller.rb:84:in `strptime'</a>
<a href='https://github.com/tannakartikey/currents/blob/809d3b2508350d866735ef6757f1e9366ba5c216/app/controllers/stripe_controller.rb#L84'>[app].../app/controllers/stripe_controller.rb:84:in `event_process'</a>
<a href='https://github.com/tannakartikey/currents/blob/809d3b2508350d866735ef6757f1e9366ba5c216/app/controllers/stripe_controller.rb#L23'>[app].../app/controllers/stripe_controller.rb:23:in `block in events'</a></pre>
Fingerprint: `7e20ffd3f21d729107727d5c84f2d9e2cc00dd53`

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>September 11, 2017 16:07:12 +0530</td></tr><tr><th>Params</th><td>#&lt;User id: 59, email: &quot;margaret.shields@kessler.com&quot;, created_at: &quot;2017-09-07 14:10:38&quot;, updated_at: &quot;2017-09-08 14:23:53&quot;, first_name: nil, last_name: nil, home_port: nil, state_waters: &quot;MA&quot;, vessel_name: nil, subscription_tier: nil, stripe_customer_id: &quot;cus_BM90KDKPzhC2EJ&quot;, subscription_id: &quot;sub_BM9BJ7IZJCCaqo&quot;, is_active: false, payment_source: nil, deleted_at: nil&gt;</td></tr></table>
