### ISSUE TITLE
#<StripeController:0xXXXXXX>#events (NameError) "undefined local variable or method `next_payment_attempt' for #<StripeController:0xXXXXXX>
Did you mean?  next_payment_attempt"

### ISSUE THREAD

**Issue by tannakartikey** [tannakartikey/currents#335]
<table><tr><th>Exception</th><td>undefined local variable or method `next_payment_attempt&#39; for #&lt;StripeController:0x0000add68a5fa0&gt;
Did you mean?  next_payment_attempt</td></tr><tr><th>Last Occurrence</th><td>September 11, 2017 16:07:45 +0530</td></tr><tr><th>Count</th><td>1</td></tr></table>

## Stack Trace
<pre><a href='https://github.com/tannakartikey/currents/blob/809d3b2508350d866735ef6757f1e9366ba5c216/app/controllers/stripe_controller.rb#L83'>[app].../app/controllers/stripe_controller.rb:83:in `event_process'</a>
<a href='https://github.com/tannakartikey/currents/blob/809d3b2508350d866735ef6757f1e9366ba5c216/app/controllers/stripe_controller.rb#L23'>[app].../app/controllers/stripe_controller.rb:23:in `block in events'</a></pre>
Fingerprint: `80f154367e012bd9679c8148fd17f87943fe87e6`

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>September 11, 2017 16:07:45 +0530</td></tr><tr><th>Params</th><td>#&lt;User id: 59, email: &quot;margaret.shields@kessler.com&quot;, created_at: &quot;2017-09-07 14:10:38&quot;, updated_at: &quot;2017-09-08 14:23:53&quot;, first_name: nil, last_name: nil, home_port: nil, state_waters: &quot;MA&quot;, vessel_name: nil, subscription_tier: nil, stripe_customer_id: &quot;cus_BM90KDKPzhC2EJ&quot;, subscription_id: &quot;sub_BM9BJ7IZJCCaqo&quot;, is_active: false, payment_source: nil, deleted_at: nil&gt;</td></tr></table>
