### ISSUE TITLE
#<StripeController:0xXXXXXX>#events (NoMethodError) "undefined method `paid' for nil:NilClass"

### ISSUE THREAD

**Issue by tannakartikey** [tannakartikey/currents#338]
<table><tr><th>Exception</th><td>undefined method `paid&#39; for nil:NilClass</td></tr><tr><th>Last Occurrence</th><td>March 11, 2018 21:12:27 +0530</td></tr><tr><th>Count</th><td>23</td></tr></table>

## Stack Trace
<pre><a href='https://github.com/tannakartikey/currents/blob/e1f8b68c108878d3c27f1b44a2bac225efdd6d2a/app/controllers/stripe_controller.rb#L72'>[app].../app/controllers/stripe_controller.rb:72:in `event_process'</a>
<a href='https://github.com/tannakartikey/currents/blob/e1f8b68c108878d3c27f1b44a2bac225efdd6d2a/app/controllers/stripe_controller.rb#L23'>[app].../app/controllers/stripe_controller.rb:23:in `block in events'</a></pre>
Fingerprint: `c50d8726956c6116d6a84c0bd5713ab8ae77e7d4`

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>October 09, 2017 16:23:56 +0530</td></tr><tr><th>Params</th><td>#&lt;User id: 12, email: &quot;tannakartikey@gmail.com&quot;, created_at: &quot;2017-08-05 15:28:27&quot;, updated_at: &quot;2017-10-09 09:33:41&quot;, first_name: &quot;Kartikey&quot;, last_name: nil, home_port: nil, state_waters: &quot;MA&quot;, vessel_name: nil, subscription_tier: nil, stripe_customer_id: &quot;cus_BJ1cLzc7y1qKmK&quot;, subscription_id: &quot;sub_BY3l47JSMQGopA&quot;, is_active: true, payment_source: &quot;src_1BAxcnLl1LzrhllYR3zPaDsp&quot;, deleted_at: nil&gt;</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>October 09, 2017 18:25:18 +0530</td></tr><tr><th>Params</th><td>#&lt;User id: 12, email: &quot;tannakartikey@gmail.com&quot;, created_at: &quot;2017-08-05 15:28:27&quot;, updated_at: &quot;2017-10-09 12:55:11&quot;, first_name: &quot;Kartikey&quot;, last_name: nil, home_port: nil, state_waters: &quot;MA&quot;, vessel_name: nil, subscription_tier: nil, stripe_customer_id: &quot;cus_BJ1cLzc7y1qKmK&quot;, subscription_id: &quot;sub_BY3l47JSMQGopA&quot;, is_active: true, payment_source: &quot;src_1BB0mlLl1LzrhllYHEoJxptI&quot;, deleted_at: nil&gt;</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>October 16, 2017 11:29:29 +0530</td></tr><tr><th>Params</th><td>#&lt;User id: 12, email: &quot;tannakartikey@gmail.com&quot;, created_at: &quot;2017-08-05 15:28:27&quot;, updated_at: &quot;2017-10-16 05:55:51&quot;, first_name: &quot;Kartikey&quot;, last_name: nil, home_port: nil, state_waters: &quot;MA&quot;, vessel_name: nil, subscription_tier: nil, stripe_customer_id: &quot;cus_BJ1cLzc7y1qKmK&quot;, subscription_id: nil, is_active: true, payment_source: &quot;src_1BDRFJLl1LzrhllYE4pLpVOp&quot;, deleted_at: nil&gt;</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>October 16, 2017 11:38:16 +0530</td></tr><tr><th>Params</th><td>#&lt;User id: 12, email: &quot;tannakartikey@gmail.com&quot;, created_at: &quot;2017-08-05 15:28:27&quot;, updated_at: &quot;2017-10-16 05:55:51&quot;, first_name: &quot;Kartikey&quot;, last_name: nil, home_port: nil, state_waters: &quot;MA&quot;, vessel_name: nil, subscription_tier: nil, stripe_customer_id: &quot;cus_BJ1cLzc7y1qKmK&quot;, subscription_id: nil, is_active: true, payment_source: &quot;src_1BDRFJLl1LzrhllYE4pLpVOp&quot;, deleted_at: nil&gt;</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>October 23, 2017 21:57:58 +0530</td></tr><tr><th>Params</th><td>#&lt;User id: 64, email: &quot;eddie.romaguera@cummings.com&quot;, created_at: &quot;2017-10-23 15:22:37&quot;, updated_at: &quot;2017-10-23 15:27:48&quot;, first_name: nil, last_name: nil, home_port: nil, state_waters: &quot;Offshore - Northeast Canyons&quot;, vessel_name: nil, subscription_tier: nil, stripe_customer_id: &quot;cus_BdOYHqGvoAoBq2&quot;, subscription_id: &quot;sub_BdOYEjGjc0LguC&quot;, is_active: false, payment_source: nil, deleted_at: nil&gt;</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>October 23, 2017 23:57:48 +0530</td></tr><tr><th>Params</th><td>#&lt;User id: 62, email: &quot;rosalind@turnertrantow.biz&quot;, created_at: &quot;2017-09-20 18:22:39&quot;, updated_at: &quot;2017-09-21 19:30:37&quot;, first_name: nil, last_name: nil, home_port: nil, state_waters: &quot;MA&quot;, vessel_name: nil, subscription_tier: nil, stripe_customer_id: &quot;cus_BR50ymWFFpNZ4s&quot;, subscription_id: &quot;sub_BR508hMxoCPe0V&quot;, is_active: true, payment_source: &quot;src_1B4JlvLl1LzrhllYovPk04RJ&quot;, deleted_at: nil&gt;</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>March 07, 2018 17:46:31 +0530</td></tr><tr><th>Params</th><td>#&lt;User id: 18, email: &quot;completetest1@email.com&quot;, created_at: &quot;2018-03-07 12:06:13&quot;, updated_at: &quot;2018-03-07 12:16:15&quot;, first_name: &quot;&quot;, last_name: &quot;&quot;, home_port: &quot;&quot;, state_waters: &quot;MA&quot;, vessel_name: &quot;&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_CRur0k6DELKyAZ&quot;, subscription_id: nil, is_active: false, payment_source: nil, deleted_at: nil&gt;</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>March 08, 2018 17:26:11 +0530</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 21, email: &quot;localtest1@email.com&quot;, created_at: &quot;2018-03-08 10:46:40&quot;, updated_at: &quot;2018-03-08 10:55:54&quot;, first_name: &quot;Local&quot;, last_name: &quot;Test1&quot;, home_port: &quot;&quot;, state_waters: &quot;MA&quot;, vessel_name: &quot;&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_CSGoZdIZypuqXq&quot;, subscription_id: &quot;sub_CSGoJMdALmKhQB&quot;, is_active: false, payment_source: nil, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>invoice.updated</td></tr><tr><th>event_id</th><td>evt_1C3NLoLl1LzrhllY6sQ3Y9Hh</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>March 10, 2018 13:12:36 +0530</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 23, email: &quot;localtest2@email.com&quot;, created_at: &quot;2018-03-10 06:34:27&quot;, updated_at: &quot;2018-03-10 06:42:24&quot;, first_name: &quot;&quot;, last_name: &quot;&quot;, home_port: &quot;&quot;, state_waters: &quot;MA&quot;, vessel_name: &quot;&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_CSxCJGQgwT32R0&quot;, subscription_id: &quot;sub_CSxCyTOv3hi30h&quot;, is_active: false, payment_source: nil, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>invoice.updated</td></tr><tr><th>event_id</th><td>evt_1C42LXLl1LzrhllYT0IXEzOw</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>March 10, 2018 16:37:51 +0530</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 6, email: &quot;abc2@email.com&quot;, created_at: &quot;2018-03-01 09:53:24&quot;, updated_at: &quot;2018-03-01 09:53:27&quot;, first_name: nil, last_name: nil, home_port: nil, state_waters: &quot;MA&quot;, vessel_name: nil, subscription_tier: nil, stripe_customer_id: &quot;cus_CPdNwClpzWosdd&quot;, subscription_id: &quot;sub_CPdN1K7okCAufU&quot;, is_active: true, payment_source: nil, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>invoice.updated</td></tr><tr><th>event_id</th><td>evt_1C45YCLl1LzrhllY9nU0ND2J</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>March 10, 2018 16:37:51 +0530</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 5, email: &quot;abc1@email.com&quot;, created_at: &quot;2018-03-01 09:39:54&quot;, updated_at: &quot;2018-03-01 09:39:57&quot;, first_name: nil, last_name: nil, home_port: nil, state_waters: &quot;MA&quot;, vessel_name: nil, subscription_tier: nil, stripe_customer_id: &quot;cus_CPd9dMa7KUj4O4&quot;, subscription_id: &quot;sub_CPd9MvFlT2JTBy&quot;, is_active: true, payment_source: nil, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>invoice.updated</td></tr><tr><th>event_id</th><td>evt_1C45YCLl1LzrhllYHblMiNDD</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>March 10, 2018 16:37:51 +0530</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 7, email: &quot;abc3@email.com&quot;, created_at: &quot;2018-03-01 09:54:22&quot;, updated_at: &quot;2018-03-01 09:54:25&quot;, first_name: nil, last_name: nil, home_port: nil, state_waters: &quot;MA&quot;, vessel_name: nil, subscription_tier: nil, stripe_customer_id: &quot;cus_CPdO3UMTQ2eDDL&quot;, subscription_id: &quot;sub_CPdOvgkc7yoIBt&quot;, is_active: true, payment_source: nil, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>invoice.updated</td></tr><tr><th>event_id</th><td>evt_1C45YCLl1LzrhllYv530539C</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>March 10, 2018 16:37:51 +0530</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 7, email: &quot;abc3@email.com&quot;, created_at: &quot;2018-03-01 09:54:22&quot;, updated_at: &quot;2018-03-10 11:07:48&quot;, first_name: nil, last_name: nil, home_port: nil, state_waters: &quot;MA&quot;, vessel_name: nil, subscription_tier: nil, stripe_customer_id: &quot;cus_CPdO3UMTQ2eDDL&quot;, subscription_id: nil, is_active: false, payment_source: nil, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>invoice.updated</td></tr><tr><th>event_id</th><td>evt_1C45YCLl1LzrhllYaLoQmv8Y</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>March 10, 2018 16:37:52 +0530</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 5, email: &quot;abc1@email.com&quot;, created_at: &quot;2018-03-01 09:39:54&quot;, updated_at: &quot;2018-03-01 09:39:57&quot;, first_name: nil, last_name: nil, home_port: nil, state_waters: &quot;MA&quot;, vessel_name: nil, subscription_tier: nil, stripe_customer_id: &quot;cus_CPd9dMa7KUj4O4&quot;, subscription_id: &quot;sub_CPd9MvFlT2JTBy&quot;, is_active: true, payment_source: nil, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>invoice.updated</td></tr><tr><th>event_id</th><td>evt_1C45YCLl1LzrhllYLK0Ym3r7</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>March 10, 2018 16:38:05 +0530</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 6, email: &quot;abc2@email.com&quot;, created_at: &quot;2018-03-01 09:53:24&quot;, updated_at: &quot;2018-03-10 11:07:50&quot;, first_name: nil, last_name: nil, home_port: nil, state_waters: &quot;MA&quot;, vessel_name: nil, subscription_tier: nil, stripe_customer_id: &quot;cus_CPdNwClpzWosdd&quot;, subscription_id: nil, is_active: false, payment_source: nil, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>invoice.updated</td></tr><tr><th>event_id</th><td>evt_1C45YCLl1LzrhllYZsB7msjp</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>March 10, 2018 17:01:44 +0530</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 8, email: &quot;abc4@email.com&quot;, created_at: &quot;2018-03-01 10:21:54&quot;, updated_at: &quot;2018-03-10 11:31:41&quot;, first_name: nil, last_name: nil, home_port: nil, state_waters: &quot;MA&quot;, vessel_name: nil, subscription_tier: nil, stripe_customer_id: &quot;cus_CPdpyIlf1ii6ES&quot;, subscription_id: nil, is_active: false, payment_source: nil, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>invoice.updated</td></tr><tr><th>event_id</th><td>evt_1C45vJLl1LzrhllY6i7OdDin</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>March 10, 2018 17:01:44 +0530</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 8, email: &quot;abc4@email.com&quot;, created_at: &quot;2018-03-01 10:21:54&quot;, updated_at: &quot;2018-03-10 11:31:41&quot;, first_name: nil, last_name: nil, home_port: nil, state_waters: &quot;MA&quot;, vessel_name: nil, subscription_tier: nil, stripe_customer_id: &quot;cus_CPdpyIlf1ii6ES&quot;, subscription_id: nil, is_active: false, payment_source: nil, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>invoice.updated</td></tr><tr><th>event_id</th><td>evt_1C45vJLl1LzrhllYK4qALr1h</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>March 10, 2018 17:39:00 +0530</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 9, email: &quot;abc5@email.com&quot;, created_at: &quot;2018-03-01 11:01:30&quot;, updated_at: &quot;2018-03-10 12:08:55&quot;, first_name: nil, last_name: nil, home_port: nil, state_waters: &quot;MA&quot;, vessel_name: nil, subscription_tier: nil, stripe_customer_id: &quot;cus_CPeTqsJT7mGrRg&quot;, subscription_id: nil, is_active: false, payment_source: nil, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>invoice.updated</td></tr><tr><th>event_id</th><td>evt_1C46VNLl1LzrhllYNPQlaMDB</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>March 10, 2018 17:39:00 +0530</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 9, email: &quot;abc5@email.com&quot;, created_at: &quot;2018-03-01 11:01:30&quot;, updated_at: &quot;2018-03-10 12:08:55&quot;, first_name: nil, last_name: nil, home_port: nil, state_waters: &quot;MA&quot;, vessel_name: nil, subscription_tier: nil, stripe_customer_id: &quot;cus_CPeTqsJT7mGrRg&quot;, subscription_id: nil, is_active: false, payment_source: nil, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>invoice.updated</td></tr><tr><th>event_id</th><td>evt_1C46VNLl1LzrhllYQHEyeVoc</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>March 10, 2018 17:49:13 +0530</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 12, email: &quot;abc8@email.com&quot;, created_at: &quot;2018-03-01 11:11:05&quot;, updated_at: &quot;2018-03-01 11:11:08&quot;, first_name: nil, last_name: nil, home_port: nil, state_waters: &quot;MA&quot;, vessel_name: nil, subscription_tier: nil, stripe_customer_id: &quot;cus_CPecCOZz3He1yL&quot;, subscription_id: &quot;sub_CPec3qTop9Ndpa&quot;, is_active: true, payment_source: nil, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>invoice.updated</td></tr><tr><th>event_id</th><td>evt_1C46fGLl1LzrhllYpx2js4Bv</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>March 10, 2018 17:49:13 +0530</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 11, email: &quot;abc7@email.com&quot;, created_at: &quot;2018-03-01 11:10:37&quot;, updated_at: &quot;2018-03-01 11:10:40&quot;, first_name: nil, last_name: nil, home_port: nil, state_waters: &quot;MA&quot;, vessel_name: nil, subscription_tier: nil, stripe_customer_id: &quot;cus_CPecDEyW8mWhSr&quot;, subscription_id: &quot;sub_CPecGpnOFbwirW&quot;, is_active: true, payment_source: nil, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>invoice.updated</td></tr><tr><th>event_id</th><td>evt_1C46fGLl1LzrhllY0hjqr01m</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>March 10, 2018 17:49:13 +0530</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 11, email: &quot;abc7@email.com&quot;, created_at: &quot;2018-03-01 11:10:37&quot;, updated_at: &quot;2018-03-01 11:10:40&quot;, first_name: nil, last_name: nil, home_port: nil, state_waters: &quot;MA&quot;, vessel_name: nil, subscription_tier: nil, stripe_customer_id: &quot;cus_CPecDEyW8mWhSr&quot;, subscription_id: &quot;sub_CPecGpnOFbwirW&quot;, is_active: true, payment_source: nil, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>invoice.updated</td></tr><tr><th>event_id</th><td>evt_1C46fGLl1LzrhllY3G1CAnro</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>March 10, 2018 17:49:12 +0530</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 10, email: &quot;abc6@email.com&quot;, created_at: &quot;2018-03-01 11:09:54&quot;, updated_at: &quot;2018-03-01 11:09:57&quot;, first_name: nil, last_name: nil, home_port: nil, state_waters: &quot;MA&quot;, vessel_name: nil, subscription_tier: nil, stripe_customer_id: &quot;cus_CPebsEto7lMQ5f&quot;, subscription_id: &quot;sub_CPebgJuyAkNyBR&quot;, is_active: true, payment_source: nil, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>invoice.updated</td></tr><tr><th>event_id</th><td>evt_1C46fGLl1LzrhllYns8OchIo</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>March 10, 2018 17:49:13 +0530</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 10, email: &quot;abc6@email.com&quot;, created_at: &quot;2018-03-01 11:09:54&quot;, updated_at: &quot;2018-03-01 11:09:57&quot;, first_name: nil, last_name: nil, home_port: nil, state_waters: &quot;MA&quot;, vessel_name: nil, subscription_tier: nil, stripe_customer_id: &quot;cus_CPebsEto7lMQ5f&quot;, subscription_id: &quot;sub_CPebgJuyAkNyBR&quot;, is_active: true, payment_source: nil, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>invoice.updated</td></tr><tr><th>event_id</th><td>evt_1C46fGLl1LzrhllYWAzEJBMc</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>March 10, 2018 17:49:14 +0530</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 12, email: &quot;abc8@email.com&quot;, created_at: &quot;2018-03-01 11:11:05&quot;, updated_at: &quot;2018-03-10 12:19:11&quot;, first_name: nil, last_name: nil, home_port: nil, state_waters: &quot;MA&quot;, vessel_name: nil, subscription_tier: nil, stripe_customer_id: &quot;cus_CPecCOZz3He1yL&quot;, subscription_id: nil, is_active: false, payment_source: nil, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>invoice.updated</td></tr><tr><th>event_id</th><td>evt_1C46fGLl1LzrhllYmcO0HUYP</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>March 10, 2018 17:49:19 +0530</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 13, email: &quot;abc9@email.com&quot;, created_at: &quot;2018-03-01 11:12:35&quot;, updated_at: &quot;2018-03-10 12:19:10&quot;, first_name: nil, last_name: nil, home_port: nil, state_waters: &quot;MA&quot;, vessel_name: nil, subscription_tier: nil, stripe_customer_id: &quot;cus_CPeevJaRLG2ywz&quot;, subscription_id: nil, is_active: false, payment_source: nil, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>invoice.updated</td></tr><tr><th>event_id</th><td>evt_1C46fGLl1LzrhllYBErRDkNl</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>March 10, 2018 19:27:14 +0530</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 13, email: &quot;abc9@email.com&quot;, created_at: &quot;2018-03-01 11:12:35&quot;, updated_at: &quot;2018-03-10 12:19:10&quot;, first_name: nil, last_name: nil, home_port: nil, state_waters: &quot;MA&quot;, vessel_name: nil, subscription_tier: nil, stripe_customer_id: &quot;cus_CPeevJaRLG2ywz&quot;, subscription_id: nil, is_active: false, payment_source: nil, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>invoice.updated</td></tr><tr><th>event_id</th><td>evt_1C46fGLl1LzrhllYpGwy703R</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>March 11, 2018 18:26:59 +0530</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 14, email: &quot;abc10@email.com&quot;, created_at: &quot;2018-03-02 05:32:44&quot;, updated_at: &quot;2018-03-02 05:32:50&quot;, first_name: nil, last_name: nil, home_port: nil, state_waters: &quot;MA&quot;, vessel_name: nil, subscription_tier: nil, stripe_customer_id: &quot;cus_CPwOQtfTBIIviS&quot;, subscription_id: &quot;sub_CPwO0CZJAFPiPv&quot;, is_active: true, payment_source: nil, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>invoice.updated</td></tr><tr><th>event_id</th><td>evt_1C4NsOLl1LzrhllYM3lzN0On</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>March 11, 2018 19:29:47 +0530</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 17, email: &quot;abc11@email.com&quot;, created_at: &quot;2018-03-02 10:57:51&quot;, updated_at: &quot;2018-03-02 10:58:02&quot;, first_name: nil, last_name: nil, home_port: nil, state_waters: &quot;MA&quot;, vessel_name: nil, subscription_tier: nil, stripe_customer_id: &quot;cus_CQ1d9xYrelwwQ0&quot;, subscription_id: &quot;sub_CQ1dXLfmRmn2ZF&quot;, is_active: true, payment_source: nil, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>invoice.updated</td></tr><tr><th>event_id</th><td>evt_1C4StfLl1LzrhllYB5McKSDp</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>March 11, 2018 19:31:08 +0530</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 16, email: &quot;vyxepy@yahoo.com&quot;, created_at: &quot;2018-03-02 10:57:14&quot;, updated_at: &quot;2018-03-02 10:57:22&quot;, first_name: &quot;&quot;, last_name: &quot;Jefferson&quot;, home_port: &quot;Esse et et occaecat quis sunt dignissimos ut nemo&quot;, state_waters: &quot;CT&quot;, vessel_name: &quot;Althea Fletcher&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_CQ1cMr2fzgdM4x&quot;, subscription_id: &quot;sub_CQ1dIr4BW8Nhv0&quot;, is_active: true, payment_source: nil, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>invoice.updated</td></tr><tr><th>event_id</th><td>evt_1C4StfLl1LzrhllYwYrG5091</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>March 11, 2018 20:46:40 +0530</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 17, email: &quot;abc11@email.com&quot;, created_at: &quot;2018-03-02 10:57:51&quot;, updated_at: &quot;2018-03-11 14:41:10&quot;, first_name: nil, last_name: nil, home_port: nil, state_waters: &quot;MA&quot;, vessel_name: nil, subscription_tier: nil, stripe_customer_id: &quot;cus_CQ1d9xYrelwwQ0&quot;, subscription_id: nil, is_active: false, payment_source: nil, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>invoice.updated</td></tr><tr><th>event_id</th><td>evt_1C4StfLl1LzrhllYrnSOkiqP</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>March 11, 2018 20:56:27 +0530</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 15, email: &quot;some1@gmail.com&quot;, created_at: &quot;2018-03-02 09:37:15&quot;, updated_at: &quot;2018-03-11 15:03:27&quot;, first_name: &quot;&quot;, last_name: &quot;&quot;, home_port: &quot;&quot;, state_waters: &quot;MA&quot;, vessel_name: &quot;&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_CQ0L35cWtbPb9n&quot;, subscription_id: nil, is_active: false, payment_source: nil, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>invoice.updated</td></tr><tr><th>event_id</th><td>evt_1C4RgJLl1LzrhllYNZDKNJSS</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>March 11, 2018 21:02:20 +0530</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 15, email: &quot;some1@gmail.com&quot;, created_at: &quot;2018-03-02 09:37:15&quot;, updated_at: &quot;2018-03-11 15:03:27&quot;, first_name: &quot;&quot;, last_name: &quot;&quot;, home_port: &quot;&quot;, state_waters: &quot;MA&quot;, vessel_name: &quot;&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_CQ0L35cWtbPb9n&quot;, subscription_id: nil, is_active: false, payment_source: nil, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>invoice.updated</td></tr><tr><th>event_id</th><td>evt_1C4RgKLl1LzrhllYQQj6Vr07</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>March 11, 2018 21:12:27 +0530</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 16, email: &quot;vyxepy@yahoo.com&quot;, created_at: &quot;2018-03-02 10:57:14&quot;, updated_at: &quot;2018-03-11 15:11:46&quot;, first_name: &quot;&quot;, last_name: &quot;Jefferson&quot;, home_port: &quot;Esse et et occaecat quis sunt dignissimos ut nemo&quot;, state_waters: &quot;CT&quot;, vessel_name: &quot;Althea Fletcher&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_CQ1cMr2fzgdM4x&quot;, subscription_id: nil, is_active: false, payment_source: nil, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>invoice.updated</td></tr><tr><th>event_id</th><td>evt_1C4SteLl1LzrhllYZm8p4JCx</td></tr></table></td></tr></table>
