### ISSUE TITLE
#<StripeController:0xXXXXXX>#events (NoMethodError) "undefined method `status' for #<Stripe::StripeObject:0xXXXXXX>"

### ISSUE THREAD

**Issue by tannakartikey** [tannakartikey/currents#339]
<table><tr><th>Exception</th><td>undefined method `status&#39; for #&lt;Stripe::StripeObject:0x007f9c4a310c20&gt;</td></tr><tr><th>Last Occurrence</th><td>June 11, 2018 11:59:57 +0000</td></tr><tr><th>Count</th><td>17</td></tr></table>

## Stack Trace
<pre>[bundle].../gems/stripe-3.3.1/lib/stripe/stripe_object.rb:285:in `method_missing'
<a href='https://github.com/tannakartikey/currents/blob/e1f8b68c108878d3c27f1b44a2bac225efdd6d2a/app/controllers/stripe_controller.rb#L50'>[app].../app/controllers/stripe_controller.rb:50:in `event_process'</a>
<a href='https://github.com/tannakartikey/currents/blob/e1f8b68c108878d3c27f1b44a2bac225efdd6d2a/app/controllers/stripe_controller.rb#L23'>[app].../app/controllers/stripe_controller.rb:23:in `block in events'</a></pre>
Fingerprint: `16c67c0a5209ccf86b5b4a9eb340c78fa747d3dc`

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>October 11, 2017 11:06:05 +0000</td></tr><tr><th>Params</th><td>#&lt;User id: 4, email: &quot;tannakartikey@gmail.com&quot;, created_at: &quot;2017-07-08 08:57:30&quot;, updated_at: &quot;2017-10-10 09:56:00&quot;, first_name: &quot;Kartikey&quot;, last_name: &quot;Tanna&quot;, home_port: &quot;&quot;, state_waters: &quot;CT&quot;, vessel_name: &quot;&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_BNVFg1D9JuGkfz&quot;, subscription_id: &quot;sub_BNarJyggCQP9aN&quot;, is_active: true, payment_source: &quot;src_1B0pfLDyDCrOMJ6PlFPrNAIh&quot;, deleted_at: nil&gt;</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>November 11, 2017 11:02:45 +0000</td></tr><tr><th>Params</th><td>#&lt;User id: 4, email: &quot;tannakartikey@gmail.com&quot;, created_at: &quot;2017-07-08 08:57:30&quot;, updated_at: &quot;2017-10-10 09:56:00&quot;, first_name: &quot;Kartikey&quot;, last_name: &quot;Tanna&quot;, home_port: &quot;&quot;, state_waters: &quot;CT&quot;, vessel_name: &quot;&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_BNVFg1D9JuGkfz&quot;, subscription_id: &quot;sub_BNarJyggCQP9aN&quot;, is_active: true, payment_source: &quot;src_1B0pfLDyDCrOMJ6PlFPrNAIh&quot;, deleted_at: nil&gt;</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>December 11, 2017 11:02:58 +0000</td></tr><tr><th>Params</th><td>#&lt;User id: 4, email: &quot;tannakartikey@gmail.com&quot;, created_at: &quot;2017-07-08 08:57:30&quot;, updated_at: &quot;2017-12-09 15:46:42&quot;, first_name: &quot;Kartikey&quot;, last_name: &quot;Tanna&quot;, home_port: &quot;&quot;, state_waters: &quot;CT&quot;, vessel_name: &quot;&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_BNVFg1D9JuGkfz&quot;, subscription_id: &quot;sub_BNarJyggCQP9aN&quot;, is_active: true, payment_source: &quot;src_1B0pfLDyDCrOMJ6PlFPrNAIh&quot;, deleted_at: nil&gt;</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>January 11, 2018 11:02:51 +0000</td></tr><tr><th>Params</th><td>#&lt;User id: 4, email: &quot;tannakartikey@gmail.com&quot;, created_at: &quot;2017-07-08 08:57:30&quot;, updated_at: &quot;2017-12-09 15:46:42&quot;, first_name: &quot;Kartikey&quot;, last_name: &quot;Tanna&quot;, home_port: &quot;&quot;, state_waters: &quot;CT&quot;, vessel_name: &quot;&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_BNVFg1D9JuGkfz&quot;, subscription_id: &quot;sub_BNarJyggCQP9aN&quot;, is_active: true, payment_source: &quot;src_1B0pfLDyDCrOMJ6PlFPrNAIh&quot;, deleted_at: nil&gt;</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>February 11, 2018 11:03:27 +0000</td></tr><tr><th>Params</th><td>#&lt;User id: 4, email: &quot;tannakartikey@gmail.com&quot;, created_at: &quot;2017-07-08 08:57:30&quot;, updated_at: &quot;2017-12-09 15:46:42&quot;, first_name: &quot;Kartikey&quot;, last_name: &quot;Tanna&quot;, home_port: &quot;&quot;, state_waters: &quot;CT&quot;, vessel_name: &quot;&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_BNVFg1D9JuGkfz&quot;, subscription_id: &quot;sub_BNarJyggCQP9aN&quot;, is_active: true, payment_source: &quot;src_1B0pfLDyDCrOMJ6PlFPrNAIh&quot;, deleted_at: nil&gt;</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>March 11, 2018 11:04:25 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 4, email: &quot;tannakartikey@gmail.com&quot;, created_at: &quot;2017-07-08 08:57:30&quot;, updated_at: &quot;2017-12-09 15:46:42&quot;, first_name: &quot;Kartikey&quot;, last_name: &quot;Tanna&quot;, home_port: &quot;&quot;, state_waters: &quot;CT&quot;, vessel_name: &quot;&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_BNVFg1D9JuGkfz&quot;, subscription_id: &quot;sub_BNarJyggCQP9aN&quot;, is_active: true, payment_source: &quot;src_1B0pfLDyDCrOMJ6PlFPrNAIh&quot;, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>customer.subscription.updated</td></tr><tr><th>event_id</th><td>evt_1C4Ry7DyDCrOMJ6PqwzWKby8</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 08, 2018 06:56:48 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 25, email: &quot;completetest1@email.com&quot;, created_at: &quot;2018-03-07 09:31:11&quot;, updated_at: &quot;2018-03-08 06:52:45&quot;, first_name: &quot;&quot;, last_name: &quot;&quot;, home_port: &quot;&quot;, state_waters: &quot;MA&quot;, vessel_name: &quot;&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_CRsMH2PSiwJHKK&quot;, subscription_id: &quot;sub_CSD2Uu8EPTvpG9&quot;, is_active: true, payment_source: &quot;src_1C3IcHDyDCrOMJ6P3xeuL6hn&quot;, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>customer.subscription.updated</td></tr><tr><th>event_id</th><td>evt_1CEXRmDyDCrOMJ6PAIxCDdA7</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 11, 2018 11:06:21 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 4, email: &quot;tannakartikey@gmail.com&quot;, created_at: &quot;2017-07-08 08:57:30&quot;, updated_at: &quot;2017-12-09 15:46:42&quot;, first_name: &quot;Kartikey&quot;, last_name: &quot;Tanna&quot;, home_port: &quot;&quot;, state_waters: &quot;CT&quot;, vessel_name: &quot;&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_BNVFg1D9JuGkfz&quot;, subscription_id: &quot;sub_BNarJyggCQP9aN&quot;, is_active: true, payment_source: &quot;src_1B0pfLDyDCrOMJ6PlFPrNAIh&quot;, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>customer.subscription.updated</td></tr><tr><th>event_id</th><td>evt_1CFglnDyDCrOMJ6PLbNf5jLg</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 11, 2018 11:39:53 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 4, email: &quot;tannakartikey@gmail.com&quot;, created_at: &quot;2017-07-08 08:57:30&quot;, updated_at: &quot;2017-12-09 15:46:42&quot;, first_name: &quot;Kartikey&quot;, last_name: &quot;Tanna&quot;, home_port: &quot;&quot;, state_waters: &quot;CT&quot;, vessel_name: &quot;&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_BNVFg1D9JuGkfz&quot;, subscription_id: &quot;sub_BNarJyggCQP9aN&quot;, is_active: true, payment_source: &quot;src_1B0pfLDyDCrOMJ6PlFPrNAIh&quot;, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>customer.subscription.updated</td></tr><tr><th>event_id</th><td>evt_1CFglnDyDCrOMJ6PLbNf5jLg</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>May 08, 2018 06:55:35 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 25, email: &quot;completetest1@email.com&quot;, created_at: &quot;2018-03-07 09:31:11&quot;, updated_at: &quot;2018-03-08 06:52:45&quot;, first_name: &quot;&quot;, last_name: &quot;&quot;, home_port: &quot;&quot;, state_waters: &quot;MA&quot;, vessel_name: &quot;&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_CRsMH2PSiwJHKK&quot;, subscription_id: &quot;sub_CSD2Uu8EPTvpG9&quot;, is_active: true, payment_source: &quot;src_1C3IcHDyDCrOMJ6P3xeuL6hn&quot;, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>customer.subscription.updated</td></tr><tr><th>event_id</th><td>evt_1CPPirDyDCrOMJ6POLpd94CR</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>May 08, 2018 08:00:13 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 25, email: &quot;completetest1@email.com&quot;, created_at: &quot;2018-03-07 09:31:11&quot;, updated_at: &quot;2018-03-08 06:52:45&quot;, first_name: &quot;&quot;, last_name: &quot;&quot;, home_port: &quot;&quot;, state_waters: &quot;MA&quot;, vessel_name: &quot;&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_CRsMH2PSiwJHKK&quot;, subscription_id: &quot;sub_CSD2Uu8EPTvpG9&quot;, is_active: true, payment_source: &quot;src_1C3IcHDyDCrOMJ6P3xeuL6hn&quot;, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>customer.subscription.updated</td></tr><tr><th>event_id</th><td>evt_1CPPirDyDCrOMJ6POLpd94CR</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>May 08, 2018 08:42:25 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 25, email: &quot;completetest1@email.com&quot;, created_at: &quot;2018-03-07 09:31:11&quot;, updated_at: &quot;2018-03-08 06:52:45&quot;, first_name: &quot;&quot;, last_name: &quot;&quot;, home_port: &quot;&quot;, state_waters: &quot;MA&quot;, vessel_name: &quot;&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_CRsMH2PSiwJHKK&quot;, subscription_id: &quot;sub_CSD2Uu8EPTvpG9&quot;, is_active: true, payment_source: &quot;src_1C3IcHDyDCrOMJ6P3xeuL6hn&quot;, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>customer.subscription.updated</td></tr><tr><th>event_id</th><td>evt_1CPPirDyDCrOMJ6POLpd94CR</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>May 11, 2018 11:02:24 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 4, email: &quot;tannakartikey@gmail.com&quot;, created_at: &quot;2017-07-08 08:57:30&quot;, updated_at: &quot;2017-12-09 15:46:42&quot;, first_name: &quot;Kartikey&quot;, last_name: &quot;Tanna&quot;, home_port: &quot;&quot;, state_waters: &quot;CT&quot;, vessel_name: &quot;&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_BNVFg1D9JuGkfz&quot;, subscription_id: &quot;sub_BNarJyggCQP9aN&quot;, is_active: true, payment_source: &quot;src_1B0pfLDyDCrOMJ6PlFPrNAIh&quot;, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>customer.subscription.updated</td></tr><tr><th>event_id</th><td>evt_1CQZ0NDyDCrOMJ6P7eSBZgxV</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>May 11, 2018 12:12:32 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 4, email: &quot;tannakartikey@gmail.com&quot;, created_at: &quot;2017-07-08 08:57:30&quot;, updated_at: &quot;2017-12-09 15:46:42&quot;, first_name: &quot;Kartikey&quot;, last_name: &quot;Tanna&quot;, home_port: &quot;&quot;, state_waters: &quot;CT&quot;, vessel_name: &quot;&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_BNVFg1D9JuGkfz&quot;, subscription_id: &quot;sub_BNarJyggCQP9aN&quot;, is_active: true, payment_source: &quot;src_1B0pfLDyDCrOMJ6PlFPrNAIh&quot;, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>customer.subscription.updated</td></tr><tr><th>event_id</th><td>evt_1CQZ0NDyDCrOMJ6P7eSBZgxV</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>June 08, 2018 06:54:39 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 25, email: &quot;completetest1@email.com&quot;, created_at: &quot;2018-03-07 09:31:11&quot;, updated_at: &quot;2018-03-08 06:52:45&quot;, first_name: &quot;&quot;, last_name: &quot;&quot;, home_port: &quot;&quot;, state_waters: &quot;MA&quot;, vessel_name: &quot;&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_CRsMH2PSiwJHKK&quot;, subscription_id: &quot;sub_CSD2Uu8EPTvpG9&quot;, is_active: true, payment_source: &quot;src_1C3IcHDyDCrOMJ6P3xeuL6hn&quot;, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>customer.subscription.updated</td></tr><tr><th>event_id</th><td>evt_1CaeUADyDCrOMJ6Pdzu1flYn</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>June 11, 2018 11:03:13 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 4, email: &quot;tannakartikey@gmail.com&quot;, created_at: &quot;2017-07-08 08:57:30&quot;, updated_at: &quot;2017-12-09 15:46:42&quot;, first_name: &quot;Kartikey&quot;, last_name: &quot;Tanna&quot;, home_port: &quot;&quot;, state_waters: &quot;CT&quot;, vessel_name: &quot;&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_BNVFg1D9JuGkfz&quot;, subscription_id: &quot;sub_BNarJyggCQP9aN&quot;, is_active: true, payment_source: &quot;src_1B0pfLDyDCrOMJ6PlFPrNAIh&quot;, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>customer.subscription.updated</td></tr><tr><th>event_id</th><td>evt_1Cbnn7DyDCrOMJ6PYAPFN5Sz</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>June 11, 2018 11:59:57 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>#&lt;User id: 4, email: &quot;tannakartikey@gmail.com&quot;, created_at: &quot;2017-07-08 08:57:30&quot;, updated_at: &quot;2017-12-09 15:46:42&quot;, first_name: &quot;Kartikey&quot;, last_name: &quot;Tanna&quot;, home_port: &quot;&quot;, state_waters: &quot;CT&quot;, vessel_name: &quot;&quot;, subscription_tier: nil, stripe_customer_id: &quot;cus_BNVFg1D9JuGkfz&quot;, subscription_id: &quot;sub_BNarJyggCQP9aN&quot;, is_active: true, payment_source: &quot;src_1B0pfLDyDCrOMJ6PlFPrNAIh&quot;, deleted_at: nil&gt;</td></tr><tr><th>event_type</th><td>customer.subscription.updated</td></tr><tr><th>event_id</th><td>evt_1Cbnn7DyDCrOMJ6PYAPFN5Sz</td></tr></table></td></tr></table>
