### ISSUE TITLE
#<StripeController:0xXXXXXX>#events (NoMethodError) "undefined method `subscription_id=' for nil:NilClass"

### ISSUE THREAD

**Issue by tannakartikey** [tannakartikey/currents#344]
<table><tr><th>Exception</th><td>undefined method `subscription_id=&#39; for nil:NilClass</td></tr><tr><th>Last Occurrence</th><td>May 03, 2018 02:56:45 +0000</td></tr><tr><th>Count</th><td>44</td></tr></table>

## Stack Trace
<pre><a href='https://github.com/tannakartikey/currents/blob/90bec523d734262be8771812124e580d5523b710/app/controllers/stripe_controller.rb#L98'>[app].../app/controllers/stripe_controller.rb:98:in `event_process'</a>
<a href='https://github.com/tannakartikey/currents/blob/90bec523d734262be8771812124e580d5523b710/app/controllers/stripe_controller.rb#L23'>[app].../app/controllers/stripe_controller.rb:23:in `block in events'</a></pre>
Fingerprint: `01285599748f57df377d1033463fc8ac9c4f7cf6`

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>November 28, 2017 14:26:15 +0000</td></tr><tr><th>Params</th><td>nil</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>February 10, 2018 22:13:03 +0000</td></tr><tr><th>Params</th><td>nil</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 09, 2018 05:13:17 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>customer.subscription.deleted</td></tr><tr><th>event_id</th><td>evt_1CEsJZDyDCrOMJ6PSzwF4XZo</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 20, 2018 02:13:45 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>customer.subscription.created</td></tr><tr><th>event_id</th><td>evt_1CIokjDyDCrOMJ6PiBhw692S</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 20, 2018 02:15:31 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>customer.subscription.deleted</td></tr><tr><th>event_id</th><td>evt_1CIombDyDCrOMJ6PgFibJ1Lh</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 20, 2018 02:15:48 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>customer.subscription.created</td></tr><tr><th>event_id</th><td>evt_1CIomnDyDCrOMJ6PGO5SPqFd</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 20, 2018 02:19:27 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>customer.subscription.deleted</td></tr><tr><th>event_id</th><td>evt_1CIoqPDyDCrOMJ6PS50wJCa0</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 20, 2018 02:19:43 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>customer.subscription.created</td></tr><tr><th>event_id</th><td>evt_1CIoqbDyDCrOMJ6Pz3rWNj6X</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 20, 2018 02:20:14 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>customer.subscription.deleted</td></tr><tr><th>event_id</th><td>evt_1CIorADyDCrOMJ6PgKYiopEV</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 20, 2018 02:20:30 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>customer.subscription.created</td></tr><tr><th>event_id</th><td>evt_1CIorMDyDCrOMJ6Pd2VC36AW</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 20, 2018 02:21:20 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>customer.subscription.deleted</td></tr><tr><th>event_id</th><td>evt_1CIosEDyDCrOMJ6PUlwZBefr</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 20, 2018 02:22:07 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>customer.subscription.created</td></tr><tr><th>event_id</th><td>evt_1CIoswDyDCrOMJ6POt8zGzYk</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 20, 2018 02:23:13 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>customer.subscription.deleted</td></tr><tr><th>event_id</th><td>evt_1CIou0DyDCrOMJ6PoYZ0RaRX</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 20, 2018 02:23:40 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>customer.subscription.created</td></tr><tr><th>event_id</th><td>evt_1CIouUDyDCrOMJ6PxWnrS6e2</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 20, 2018 02:24:07 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>customer.subscription.deleted</td></tr><tr><th>event_id</th><td>evt_1CIoutDyDCrOMJ6POzTMOd3c</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 20, 2018 02:25:00 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>customer.subscription.created</td></tr><tr><th>event_id</th><td>evt_1CIovnDyDCrOMJ6PD9bcAiCX</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 20, 2018 02:25:39 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>customer.subscription.deleted</td></tr><tr><th>event_id</th><td>evt_1CIowPDyDCrOMJ6PZWayDCHe</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 20, 2018 02:26:04 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>customer.subscription.created</td></tr><tr><th>event_id</th><td>evt_1CIowlDyDCrOMJ6PxZKDmwA7</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 20, 2018 17:17:54 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>customer.subscription.created</td></tr><tr><th>event_id</th><td>evt_1CJ2roDyDCrOMJ6PiaKJ1Tze</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 20, 2018 17:17:55 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>customer.subscription.deleted</td></tr><tr><th>event_id</th><td>evt_1CJ2rJDyDCrOMJ6PcQms1hQ4</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 20, 2018 17:25:47 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>customer.subscription.deleted</td></tr><tr><th>event_id</th><td>evt_1CJ2zUDyDCrOMJ6PU9z1mySy</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 20, 2018 18:13:00 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>customer.subscription.deleted</td></tr><tr><th>event_id</th><td>evt_1CJ2rJDyDCrOMJ6PcQms1hQ4</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 20, 2018 19:33:28 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>customer.subscription.deleted</td></tr><tr><th>event_id</th><td>evt_1CJ2rJDyDCrOMJ6PcQms1hQ4</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 20, 2018 20:18:21 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>customer.subscription.deleted</td></tr><tr><th>event_id</th><td>evt_1CJ2rJDyDCrOMJ6PcQms1hQ4</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 20, 2018 21:19:13 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>customer.subscription.deleted</td></tr><tr><th>event_id</th><td>evt_1CJ2rJDyDCrOMJ6PcQms1hQ4</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 23, 2018 19:15:45 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>customer.subscription.created</td></tr><tr><th>event_id</th><td>evt_1CKA7qDyDCrOMJ6P4xr9HS97</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 23, 2018 19:19:26 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>customer.subscription.deleted</td></tr><tr><th>event_id</th><td>evt_1CKAC6DyDCrOMJ6P72AZLfJg</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 23, 2018 19:19:59 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>customer.subscription.created</td></tr><tr><th>event_id</th><td>evt_1CKACdDyDCrOMJ6PhzEnXk7d</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 23, 2018 19:22:49 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>customer.subscription.deleted</td></tr><tr><th>event_id</th><td>evt_1CKAFMDyDCrOMJ6PHi35yJg5</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 23, 2018 19:26:17 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>customer.subscription.created</td></tr><tr><th>event_id</th><td>evt_1CKAIhDyDCrOMJ6PwbamXfQw</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 23, 2018 19:29:35 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>customer.subscription.deleted</td></tr><tr><th>event_id</th><td>evt_1CKALwDyDCrOMJ6PK9lK7HQC</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 23, 2018 19:29:44 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>customer.subscription.created</td></tr><tr><th>event_id</th><td>evt_1CKAM5DyDCrOMJ6P4Y8yxOjl</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 23, 2018 19:31:03 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>customer.subscription.deleted</td></tr><tr><th>event_id</th><td>evt_1CKANIDyDCrOMJ6P5w4BQw1z</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 23, 2018 19:31:16 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>customer.subscription.created</td></tr><tr><th>event_id</th><td>evt_1CKANXDyDCrOMJ6PjzdZo5LL</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 23, 2018 19:56:26 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>customer.subscription.deleted</td></tr><tr><th>event_id</th><td>evt_1CKAlwDyDCrOMJ6PrfXMK64k</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 23, 2018 19:57:02 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>customer.subscription.created</td></tr><tr><th>event_id</th><td>evt_1CKAmUDyDCrOMJ6PPBihPR2i</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 23, 2018 20:15:45 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>customer.subscription.created</td></tr><tr><th>event_id</th><td>evt_1CKA7qDyDCrOMJ6P4xr9HS97</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 24, 2018 01:12:19 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>customer.subscription.created</td></tr><tr><th>event_id</th><td>evt_1CKFhTDyDCrOMJ6PDI5QBzgA</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 24, 2018 01:12:20 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>customer.subscription.deleted</td></tr><tr><th>event_id</th><td>evt_1CKFh6DyDCrOMJ6PDuylemIG</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 24, 2018 01:21:38 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>customer.subscription.deleted</td></tr><tr><th>event_id</th><td>evt_1CKFqcDyDCrOMJ6Px4tCw9Lg</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 24, 2018 01:22:06 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>customer.subscription.created</td></tr><tr><th>event_id</th><td>evt_1CKFr5DyDCrOMJ6PUfWvZjdC</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 24, 2018 02:07:24 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>customer.subscription.deleted</td></tr><tr><th>event_id</th><td>evt_1CKFh6DyDCrOMJ6PDuylemIG</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 24, 2018 03:02:19 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>customer.subscription.deleted</td></tr><tr><th>event_id</th><td>evt_1CKFh6DyDCrOMJ6PDuylemIG</td></tr></table></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>May 03, 2018 02:56:45 +0000</td></tr><tr><th>Params</th><td><table><tr><th>user</th><td>nil</td></tr><tr><th>event_type</th><td>customer.subscription.created</td></tr><tr><th>event_id</th><td>evt_1CNXcGDyDCrOMJ6PLyKzBqi2</td></tr></table></td></tr></table>
