### ISSUE TITLE
#<StripeController:0xXXXXXX>#events (NoMethodError) "undefined method `subscription_id=' for nil:NilClass"

### ISSUE THREAD

**Issue by tannakartikey** [tannakartikey/currents#345]
<table><tr><th>Exception</th><td>undefined method `subscription_id=&#39; for nil:NilClass</td></tr><tr><th>Last Occurrence</th><td>February 08, 2018 15:03:54 +0000</td></tr><tr><th>Count</th><td>17</td></tr></table>

## Stack Trace
<pre><a href='https://github.com/tannakartikey/currents/blob/90bec523d734262be8771812124e580d5523b710/app/controllers/stripe_controller.rb#L98'>[app].../app/controllers/stripe_controller.rb:98:in `event_process'</a>
<a href='https://github.com/tannakartikey/currents/blob/90bec523d734262be8771812124e580d5523b710/app/controllers/stripe_controller.rb#L23'>[app].../app/controllers/stripe_controller.rb:23:in `block in events'</a></pre>
Fingerprint: `01285599748f57df377d1033463fc8ac9c4f7cf6`

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>November 28, 2017 14:26:16 +0000</td></tr><tr><th>Params</th><td>nil</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>December 13, 2017 15:32:56 +0000</td></tr><tr><th>Params</th><td>nil</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>December 13, 2017 15:32:57 +0000</td></tr><tr><th>Params</th><td>nil</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>December 18, 2017 22:11:32 +0000</td></tr><tr><th>Params</th><td>nil</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>December 18, 2017 22:15:11 +0000</td></tr><tr><th>Params</th><td>nil</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>December 18, 2017 22:15:54 +0000</td></tr><tr><th>Params</th><td>nil</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>December 18, 2017 22:16:44 +0000</td></tr><tr><th>Params</th><td>nil</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>December 18, 2017 22:55:58 +0000</td></tr><tr><th>Params</th><td>nil</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>January 02, 2018 23:22:31 +0000</td></tr><tr><th>Params</th><td>nil</td></tr></table>
