### ISSUE TITLE
# (RuntimeError) "ABC"

### ISSUE THREAD

**Issue by tannakartikey** [tannakartikey/currents#352]
<table><tr><th>Exception</th><td>ABC</td></tr><tr><th>Last Occurrence</th><td>February 11, 2018 13:57:52 +0530</td></tr><tr><th>Count</th><td>1</td></tr></table>

## Stack Trace
<pre><a href='https://github.com/tannakartikey/currents/blob/e0ccb2ac8b35d7ddb47f801764036410f08f90fd/app/models/stripe_customer.rb#L4'>[app].../app/models/stripe_customer.rb:4:in `raise_error'</a>
<a href='https://github.com/tannakartikey/currents/blob/e0ccb2ac8b35d7ddb47f801764036410f08f90fd/app/models/exception_wrapper.rb#L11'>[app].../app/models/exception_wrapper.rb:11:in `call'</a>
<a href='https://github.com/tannakartikey/currents/blob/e0ccb2ac8b35d7ddb47f801764036410f08f90fd/app/models/exception_wrapper.rb#L11'>[app].../app/models/exception_wrapper.rb:11:in `block (2 levels) in singleton class'</a>
(pry):3:in `<main>'
[bundle].../gems/pry-0.10.4/lib/pry/pry_instance.rb:355:in `eval'
[bundle].../gems/pry-0.10.4/lib/pry/pry_instance.rb:355:in `evaluate_ruby'
[bundle].../gems/pry-0.10.4/lib/pry/pry_instance.rb:323:in `handle_line'
[bundle].../gems/pry-0.10.4/lib/pry/pry_instance.rb:243:in `block (2 levels) in eval'
[bundle].../gems/pry-0.10.4/lib/pry/pry_instance.rb:242:in `catch'
[bundle].../gems/pry-0.10.4/lib/pry/pry_instance.rb:242:in `block in eval'
[bundle].../gems/pry-0.10.4/lib/pry/pry_instance.rb:241:in `catch'
[bundle].../gems/pry-0.10.4/lib/pry/pry_instance.rb:241:in `eval'
[bundle].../gems/pry-0.10.4/lib/pry/repl.rb:77:in `block in repl'
[bundle].../gems/pry-0.10.4/lib/pry/repl.rb:67:in `loop'
[bundle].../gems/pry-0.10.4/lib/pry/repl.rb:67:in `repl'
[bundle].../gems/pry-0.10.4/lib/pry/repl.rb:38:in `block in start'
[bundle].../gems/pry-0.10.4/lib/pry/input_lock.rb:61:in `__with_ownership'
[bundle].../gems/pry-0.10.4/lib/pry/input_lock.rb:79:in `with_ownership'
[bundle].../gems/pry-0.10.4/lib/pry/repl.rb:38:in `start'
[bundle].../gems/pry-0.10.4/lib/pry/repl.rb:15:in `start'
[bundle].../gems/pry-0.10.4/lib/pry/pry_class.rb:169:in `start'
[bundle].../gems/pry-byebug-3.4.2/lib/pry-byebug/pry_ext.rb:11:in `start_with_pry_byebug'
[bundle].../gems/railties-4.2.7.1/lib/rails/commands/console.rb:110:in `start'
[bundle].../gems/railties-4.2.7.1/lib/rails/commands/console.rb:9:in `start'
[bundle].../gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:68:in `console'
[bundle].../gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
[bundle].../gems/railties-4.2.7.1/lib/rails/commands.rb:17:in `<top (required)>'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
<a href='https://github.com/tannakartikey/currents/blob/e0ccb2ac8b35d7ddb47f801764036410f08f90fd/bin/rails#L9'>[app].../bin/rails:9:in `<top (required)>'</a>
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `block in load'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
/home/kartikey/.rbenv/versions/2.3.4/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/home/kartikey/.rbenv/versions/2.3.4/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
-e:1:in `<main>'</pre>
Fingerprint: `fcec76cd3f075c2951f8c94f3df15a26dfcb72ca`

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>February 11, 2018 13:57:52 +0530</td></tr><tr><th>Params</th><td>nil</td></tr></table>
