### ISSUE TITLE
filter_by_species#render_coordinate_file (Errno::ENOENT) "No such file or directory @ rb_sysopen - /home/kartikey/source/currents/public/uploads/location/coordinate_file/dummy_location_data.json"

### ISSUE THREAD

**Issue by tannakartikey** [tannakartikey/currents#363]
<table><tr><th>Exception</th><td>No such file or directory @ rb_sysopen - /home/kartikey/source/currents/public/uploads/location/coordinate_file/dummy_location_data.json</td></tr><tr><th>Last Occurrence</th><td>April 26, 2019 22:06:22 +0530</td></tr><tr><th>Count</th><td>38</td></tr></table>

## Stack Trace
<pre>[bundle].../gems/carrierwave-1.1.0/lib/carrierwave/sanitized_file.rb:163:in `initialize'
[bundle].../gems/carrierwave-1.1.0/lib/carrierwave/sanitized_file.rb:163:in `open'
[bundle].../gems/carrierwave-1.1.0/lib/carrierwave/sanitized_file.rb:163:in `read'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/core_ext/object/try.rb:77:in `public_send'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/core_ext/object/try.rb:77:in `try!'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/core_ext/object/try.rb:63:in `try'
[bundle].../gems/carrierwave-1.1.0/lib/carrierwave/uploader/proxy.rb:44:in `read'
<a href='https://github.com/tannakartikey/currents/blob/8655c724d41956bb054a62b9a9a8790ee99f8c16/app/models/filter_by_species.rb#L38'>[app].../app/models/filter_by_species.rb:38:in `render_coordinate_file'</a>
<a href='https://github.com/tannakartikey/currents/blob/8655c724d41956bb054a62b9a9a8790ee99f8c16/app/models/filter_by_species.rb#L22'>[app].../app/models/filter_by_species.rb:22:in `block in maps_data'</a>
[bundle].../gems/activerecord-4.2.7.1/lib/active_record/relation/delegation.rb:46:in `each'
[bundle].../gems/activerecord-4.2.7.1/lib/active_record/relation/delegation.rb:46:in `each'
<a href='https://github.com/tannakartikey/currents/blob/8655c724d41956bb054a62b9a9a8790ee99f8c16/app/models/filter_by_species.rb#L9'>[app].../app/models/filter_by_species.rb:9:in `maps_data'</a>
<a href='https://github.com/tannakartikey/currents/blob/8655c724d41956bb054a62b9a9a8790ee99f8c16/app/controllers/maps_controller.rb#L19'>[app].../app/controllers/maps_controller.rb:19:in `filter_by_species'</a>
[bundle].../gems/actionpack-4.2.7.1/lib/action_controller/metal/implicit_render.rb:4:in `send_action'
[bundle].../gems/actionpack-4.2.7.1/lib/abstract_controller/base.rb:198:in `process_action'
[bundle].../gems/actionpack-4.2.7.1/lib/action_controller/metal/rendering.rb:10:in `process_action'
[bundle].../gems/actionpack-4.2.7.1/lib/abstract_controller/callbacks.rb:20:in `block in process_action'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:117:in `call'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:555:in `block (2 levels) in compile'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:505:in `call'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:498:in `block (2 levels) in around'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:313:in `block (2 levels) in halting'
[bundle].../gems/sentry-raven-2.7.2/lib/raven/integrations/rails/controller_transaction.rb:7:in `block in included'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:441:in `instance_exec'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:441:in `block in make_lambda'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:312:in `block in halting'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:497:in `block in around'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:505:in `call'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:92:in `__run_callbacks__'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_process_action_callbacks'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
[bundle].../gems/actionpack-4.2.7.1/lib/abstract_controller/callbacks.rb:19:in `process_action'
[bundle].../gems/actionpack-4.2.7.1/lib/action_controller/metal/rescue.rb:29:in `process_action'
[bundle].../gems/actionpack-4.2.7.1/lib/action_controller/metal/instrumentation.rb:32:in `block in process_action'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `block in instrument'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/notifications/instrumenter.rb:20:in `instrument'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/notifications.rb:164:in `instrument'
[bundle].../gems/actionpack-4.2.7.1/lib/action_controller/metal/instrumentation.rb:30:in `process_action'
[bundle].../gems/actionpack-4.2.7.1/lib/action_controller/metal/params_wrapper.rb:250:in `process_action'
[bundle].../gems/activerecord-4.2.7.1/lib/active_record/railties/controller_runtime.rb:18:in `process_action'
[bundle].../gems/actionpack-4.2.7.1/lib/abstract_controller/base.rb:137:in `process'
[bundle].../gems/actionview-4.2.7.1/lib/action_view/rendering.rb:30:in `process'
[bundle].../gems/rack-mini-profiler-0.10.5/lib/mini_profiler/profiling_methods.rb:102:in `block in profile_method'
[bundle].../gems/actionpack-4.2.7.1/lib/action_controller/metal.rb:196:in `dispatch'
[bundle].../gems/actionpack-4.2.7.1/lib/action_controller/metal/rack_delegation.rb:13:in `dispatch'
[bundle].../gems/actionpack-4.2.7.1/lib/action_controller/metal.rb:237:in `block in action'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/routing/route_set.rb:74:in `dispatch'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/routing/route_set.rb:43:in `serve'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/journey/router.rb:43:in `block in serve'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/journey/router.rb:30:in `each'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/journey/router.rb:30:in `serve'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/routing/route_set.rb:817:in `call'
[bundle].../gems/warden-1.2.7/lib/warden/manager.rb:36:in `block in call'
[bundle].../gems/warden-1.2.7/lib/warden/manager.rb:35:in `catch'
[bundle].../gems/warden-1.2.7/lib/warden/manager.rb:35:in `call'
[bundle].../gems/rack-1.6.10/lib/rack/etag.rb:24:in `call'
[bundle].../gems/rack-1.6.10/lib/rack/conditionalget.rb:25:in `call'
[bundle].../gems/rack-1.6.10/lib/rack/head.rb:13:in `call'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/params_parser.rb:27:in `call'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/flash.rb:260:in `call'
[bundle].../gems/rack-1.6.10/lib/rack/session/abstract/id.rb:225:in `context'
[bundle].../gems/rack-1.6.10/lib/rack/session/abstract/id.rb:220:in `call'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/cookies.rb:560:in `call'
[bundle].../gems/activerecord-4.2.7.1/lib/active_record/query_cache.rb:36:in `call'
[bundle].../gems/activerecord-4.2.7.1/lib/active_record/connection_adapters/abstract/connection_pool.rb:653:in `call'
[bundle].../gems/activerecord-4.2.7.1/lib/active_record/migration.rb:377:in `call'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/callbacks.rb:29:in `block in call'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:88:in `__run_callbacks__'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:778:in `_run_call_callbacks'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/callbacks.rb:81:in `run_callbacks'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/callbacks.rb:27:in `call'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/reloader.rb:73:in `call'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/remote_ip.rb:78:in `call'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/debug_exceptions.rb:17:in `call'
[bundle].../gems/web-console-2.3.0/lib/web_console/middleware.rb:28:in `block in call'
[bundle].../gems/web-console-2.3.0/lib/web_console/middleware.rb:18:in `catch'
[bundle].../gems/web-console-2.3.0/lib/web_console/middleware.rb:18:in `call'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/show_exceptions.rb:30:in `call'
[bundle].../gems/railties-4.2.7.1/lib/rails/rack/logger.rb:38:in `call_app'
[bundle].../gems/railties-4.2.7.1/lib/rails/rack/logger.rb:20:in `block in call'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:68:in `block in tagged'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:26:in `tagged'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/tagged_logging.rb:68:in `tagged'
[bundle].../gems/railties-4.2.7.1/lib/rails/rack/logger.rb:20:in `call'
[bundle].../gems/quiet_assets-1.1.0/lib/quiet_assets.rb:27:in `call_with_quiet_assets'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/request_id.rb:21:in `call'
[bundle].../gems/rack-1.6.10/lib/rack/methodoverride.rb:22:in `call'
[bundle].../gems/rack-1.6.10/lib/rack/runtime.rb:18:in `call'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/cache/strategy/local_cache_middleware.rb:28:in `call'
[bundle].../gems/rack-1.6.10/lib/rack/lock.rb:17:in `call'
[bundle].../gems/rack-livereload-0.3.16/lib/rack/livereload.rb:23:in `_call'
[bundle].../gems/rack-livereload-0.3.16/lib/rack/livereload.rb:14:in `call'
[bundle].../gems/actionpack-4.2.7.1/lib/action_dispatch/middleware/static.rb:120:in `call'
[bundle].../gems/rack-1.6.10/lib/rack/sendfile.rb:113:in `call'
[bundle].../gems/sentry-raven-2.7.2/lib/raven/integrations/rack.rb:51:in `call'
[bundle].../gems/rack-mini-profiler-0.10.5/lib/mini_profiler/profiler.rb:282:in `call'
[bundle].../gems/railties-4.2.7.1/lib/rails/engine.rb:518:in `call'
[bundle].../gems/railties-4.2.7.1/lib/rails/application.rb:165:in `call'
[bundle].../gems/rack-1.6.10/lib/rack/content_length.rb:15:in `call'
[bundle].../gems/puma-3.9.1/lib/puma/configuration.rb:224:in `call'
[bundle].../gems/puma-3.9.1/lib/puma/server.rb:602:in `handle_request'
[bundle].../gems/puma-3.9.1/lib/puma/server.rb:435:in `process_client'
[bundle].../gems/puma-3.9.1/lib/puma/server.rb:299:in `block in run'
[bundle].../gems/puma-3.9.1/lib/puma/thread_pool.rb:120:in `block in spawn_thread'</pre>
Fingerprint: `ca6c8ef199bffebbeb263d00d3ab860f8ebd7d8d`

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 26, 2019 20:03:33 +0530</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 26, 2019 20:03:39 +0530</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 26, 2019 20:03:48 +0530</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 26, 2019 20:04:23 +0530</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 26, 2019 20:04:30 +0530</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 26, 2019 20:04:37 +0530</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 26, 2019 20:06:34 +0530</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 26, 2019 20:06:41 +0530</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 26, 2019 20:06:49 +0530</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 26, 2019 20:18:55 +0530</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 26, 2019 20:19:02 +0530</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 26, 2019 20:19:11 +0530</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 26, 2019 20:19:23 +0530</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 26, 2019 20:19:31 +0530</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 26, 2019 20:19:39 +0530</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 26, 2019 22:01:27 +0530</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 26, 2019 22:01:31 +0530</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 26, 2019 22:01:36 +0530</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 26, 2019 22:03:15 +0530</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 26, 2019 22:03:20 +0530</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 26, 2019 22:03:27 +0530</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 26, 2019 22:03:37 +0530</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 26, 2019 22:03:41 +0530</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 26, 2019 22:03:48 +0530</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 26, 2019 22:04:29 +0530</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 26, 2019 22:04:34 +0530</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 26, 2019 22:04:39 +0530</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 26, 2019 22:04:52 +0530</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 26, 2019 22:04:57 +0530</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 26, 2019 22:05:05 +0530</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 26, 2019 22:05:19 +0530</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 26, 2019 22:05:24 +0530</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 26, 2019 22:05:29 +0530</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 26, 2019 22:05:34 +0530</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 26, 2019 22:05:38 +0530</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 26, 2019 22:05:43 +0530</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 26, 2019 22:05:54 +0530</td></tr><tr><th>Params</th><td></td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>April 26, 2019 22:06:22 +0530</td></tr><tr><th>Params</th><td></td></tr></table>
