### ISSUE TITLE
#retrieve (Stripe::InvalidRequestError) "No such customer: 123"

### ISSUE THREAD

**Issue by tannakartikey** [tannakartikey/currents#40]
<table><tr><th>Exception</th><td>(Status 404) (Request req_uYZWH4bQ0ORKkb) No such customer: 123</td></tr><tr><th>Last Occurrence</th><td>August 14, 2017 12:47:10 +0530</td></tr><tr><th>Count</th><td>4</td></tr></table>

## Stack Trace
<pre>[bundle].../gems/stripe-3.0.0/lib/stripe/stripe_client.rb:253:in `handle_error_response'
[bundle].../gems/stripe-3.0.0/lib/stripe/stripe_client.rb:200:in `rescue in execute_request_with_rescues'
[bundle].../gems/stripe-3.0.0/lib/stripe/stripe_client.rb:184:in `execute_request_with_rescues'
[bundle].../gems/stripe-3.0.0/lib/stripe/stripe_client.rb:136:in `execute_request'
[bundle].../gems/stripe-3.0.0/lib/stripe/api_operations/request.rb:19:in `request'
[bundle].../gems/stripe-3.0.0/lib/stripe/api_operations/request.rb:58:in `request'
[bundle].../gems/stripe-3.0.0/lib/stripe/api_resource.rb:57:in `refresh'
[bundle].../gems/stripe-3.0.0/lib/stripe/api_resource.rb:64:in `retrieve'
<a href='https://github.com/tannakartikey/currents/blob/f473102edffc6f494cdb3650ddbaabc4478b5eee/app/models/stripe_customer.rb#L11'>[app].../app/models/stripe_customer.rb:11:in `retrieve'</a>
(pry):43:in `<main>'
[bundle].../gems/pry-0.10.4/lib/pry/pry_instance.rb:355:in `eval'
[bundle].../gems/pry-0.10.4/lib/pry/pry_instance.rb:355:in `evaluate_ruby'
[bundle].../gems/pry-0.10.4/lib/pry/pry_instance.rb:323:in `handle_line'
[bundle].../gems/pry-0.10.4/lib/pry/pry_instance.rb:243:in `block (2 levels) in eval'
[bundle].../gems/pry-0.10.4/lib/pry/pry_instance.rb:242:in `catch'
[bundle].../gems/pry-0.10.4/lib/pry/pry_instance.rb:242:in `block in eval'
[bundle].../gems/pry-0.10.4/lib/pry/pry_instance.rb:241:in `catch'
[bundle].../gems/pry-0.10.4/lib/pry/pry_instance.rb:241:in `eval'
[bundle].../gems/pry-0.10.4/lib/pry/repl.rb:77:in `block in repl'
[bundle].../gems/pry-0.10.4/lib/pry/repl.rb:67:in `loop'
[bundle].../gems/pry-0.10.4/lib/pry/repl.rb:67:in `repl'
[bundle].../gems/pry-0.10.4/lib/pry/repl.rb:38:in `block in start'
[bundle].../gems/pry-0.10.4/lib/pry/input_lock.rb:61:in `__with_ownership'
[bundle].../gems/pry-0.10.4/lib/pry/input_lock.rb:79:in `with_ownership'
[bundle].../gems/pry-0.10.4/lib/pry/repl.rb:38:in `start'
[bundle].../gems/pry-0.10.4/lib/pry/repl.rb:15:in `start'
[bundle].../gems/pry-0.10.4/lib/pry/pry_class.rb:169:in `start'
[bundle].../gems/pry-byebug-3.4.2/lib/pry-byebug/pry_ext.rb:11:in `start_with_pry_byebug'
[bundle].../gems/railties-4.2.7.1/lib/rails/commands/console.rb:110:in `start'
[bundle].../gems/railties-4.2.7.1/lib/rails/commands/console.rb:9:in `start'
[bundle].../gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:68:in `console'
[bundle].../gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
[bundle].../gems/railties-4.2.7.1/lib/rails/commands.rb:17:in `<top (required)>'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
<a href='https://github.com/tannakartikey/currents/blob/f473102edffc6f494cdb3650ddbaabc4478b5eee/bin/rails#L9'>[app].../bin/rails:9:in `<top (required)>'</a>
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `block in load'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
/home/kartikey/.rbenv/versions/2.3.4/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/home/kartikey/.rbenv/versions/2.3.4/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
-e:1:in `<main>'</pre>
Fingerprint: `6c2e29d0b01069a8982f5f37ff41d3cc3eb98722`

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 14, 2017 12:43:22 +0530</td></tr><tr><th>Params</th><td>error occured while creating stirpe custoemr for</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 14, 2017 12:45:20 +0530</td></tr><tr><th>Params</th><td>error occured while creating stirpe custoemr for </td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 14, 2017 12:46:22 +0530</td></tr><tr><th>Params</th><td>error occured while creating stirpe custoemr for </td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 14, 2017 12:47:10 +0530</td></tr><tr><th>Params</th><td>error occured while creating stirpe custoemr for dummy@web.com</td></tr></table>
