### ISSUE TITLE
# (Stripe::InvalidRequestError) "Could not determine which URL to request: Stripe::Subscription instance has invalid ID: nil"

### ISSUE THREAD

**Issue by tannakartikey** [tannakartikey/currents#41]
<table><tr><th>Exception</th><td>Could not determine which URL to request: Stripe::Subscription instance has invalid ID: nil</td></tr><tr><th>Last Occurrence</th><td>August 17, 2017 00:44:28 +0530</td></tr><tr><th>Count</th><td>8</td></tr></table>

## Stack Trace
<pre>[bundle].../gems/stripe-3.0.0/lib/stripe/api_resource.rb:51:in `resource_url'
[bundle].../gems/stripe-3.0.0/lib/stripe/api_resource.rb:57:in `refresh'
[bundle].../gems/stripe-3.0.0/lib/stripe/api_resource.rb:64:in `retrieve'
<a href='https://github.com/tannakartikey/currents/blob/f473102edffc6f494cdb3650ddbaabc4478b5eee/app/models/stripe_subscription.rb#L20'>[app].../app/models/stripe_subscription.rb:20:in `block in retrieve'</a>
<a href='https://github.com/tannakartikey/currents/blob/f473102edffc6f494cdb3650ddbaabc4478b5eee/app/models/stripe_subscription.rb#L4'>[app].../app/models/stripe_subscription.rb:4:in `handler'</a>
<a href='https://github.com/tannakartikey/currents/blob/f473102edffc6f494cdb3650ddbaabc4478b5eee/app/models/stripe_subscription.rb#L20'>[app].../app/models/stripe_subscription.rb:20:in `retrieve'</a>
(pry):15:in `<main>'
[bundle].../gems/pry-0.10.4/lib/pry/pry_instance.rb:355:in `eval'
[bundle].../gems/pry-0.10.4/lib/pry/pry_instance.rb:355:in `evaluate_ruby'
[bundle].../gems/pry-0.10.4/lib/pry/pry_instance.rb:323:in `handle_line'
[bundle].../gems/pry-0.10.4/lib/pry/pry_instance.rb:243:in `block (2 levels) in eval'
[bundle].../gems/pry-0.10.4/lib/pry/pry_instance.rb:242:in `catch'
[bundle].../gems/pry-0.10.4/lib/pry/pry_instance.rb:242:in `block in eval'
[bundle].../gems/pry-0.10.4/lib/pry/pry_instance.rb:241:in `catch'
[bundle].../gems/pry-0.10.4/lib/pry/pry_instance.rb:241:in `eval'
[bundle].../gems/pry-0.10.4/lib/pry/repl.rb:77:in `block in repl'
[bundle].../gems/pry-0.10.4/lib/pry/repl.rb:67:in `loop'
[bundle].../gems/pry-0.10.4/lib/pry/repl.rb:67:in `repl'
[bundle].../gems/pry-0.10.4/lib/pry/repl.rb:38:in `block in start'
[bundle].../gems/pry-0.10.4/lib/pry/input_lock.rb:61:in `__with_ownership'
[bundle].../gems/pry-0.10.4/lib/pry/input_lock.rb:79:in `with_ownership'
[bundle].../gems/pry-0.10.4/lib/pry/repl.rb:38:in `start'
[bundle].../gems/pry-0.10.4/lib/pry/repl.rb:15:in `start'
[bundle].../gems/pry-0.10.4/lib/pry/pry_class.rb:169:in `start'
[bundle].../gems/pry-byebug-3.4.2/lib/pry-byebug/pry_ext.rb:11:in `start_with_pry_byebug'
[bundle].../gems/railties-4.2.7.1/lib/rails/commands/console.rb:110:in `start'
[bundle].../gems/railties-4.2.7.1/lib/rails/commands/console.rb:9:in `start'
[bundle].../gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:68:in `console'
[bundle].../gems/railties-4.2.7.1/lib/rails/commands/commands_tasks.rb:39:in `run_command!'
[bundle].../gems/railties-4.2.7.1/lib/rails/commands.rb:17:in `<top (required)>'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `block in require'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:274:in `require'
<a href='https://github.com/tannakartikey/currents/blob/f473102edffc6f494cdb3650ddbaabc4478b5eee/bin/rails#L9'>[app].../bin/rails:9:in `<top (required)>'</a>
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `block in load'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:240:in `load_dependency'
[bundle].../gems/activesupport-4.2.7.1/lib/active_support/dependencies.rb:268:in `load'
/home/kartikey/.rbenv/versions/2.3.4/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/home/kartikey/.rbenv/versions/2.3.4/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
-e:1:in `<main>'</pre>
Fingerprint: `883b0ead6f7a04796def91ba22024e0f8c248539`

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 14, 2017 20:20:08 +0530</td></tr><tr><th>Params</th><td>fakeaccount@mailinator.com</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 14, 2017 21:38:31 +0530</td></tr><tr><th>Params</th><td>fakeaccount@mailinator.com</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 14, 2017 21:39:16 +0530</td></tr><tr><th>Params</th><td>fakeaccount@mailinator.com</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 14, 2017 21:45:36 +0530</td></tr><tr><th>Params</th><td>fakeaccount@mailinator.com</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 17, 2017 00:36:35 +0530</td></tr><tr><th>Params</th><td>marlo@schoen.biz</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 17, 2017 00:39:59 +0530</td></tr><tr><th>Params</th><td>--- &#39;#&lt;User id: 2, email: &quot;marlo@schoen.biz&quot;, created_at: &quot;2017-08-04 09:07:51&quot;, updated_at:
  &quot;2017-08-16 19:01:56&quot;, first_name: &quot;First_Name&quot;, last_name: nil, home_port: nil,
  state_waters: &quot;MA&quot;, vessel_name: nil, subscription_tier: nil, stripe_customer_id:
  &quot;cus_B9NoFAwamZzZok&quot;, subscription_id: nil, is_active: false, payment_source: nil,
  deleted_at: nil&gt;&#39;
</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 17, 2017 00:43:21 +0530</td></tr><tr><th>Params</th><td>{
  &quot;id&quot;: 2,
  &quot;email&quot;: &quot;marlo@schoen.biz&quot;,
  &quot;created_at&quot;: &quot;2017-08-04 09:07:51 UTC&quot;,
  &quot;updated_at&quot;: &quot;2017-08-16 19:01:56 UTC&quot;,
  &quot;first_name&quot;: &quot;First_Name&quot;,
  &quot;last_name&quot;: null,
  &quot;home_port&quot;: null,
  &quot;state_waters&quot;: &quot;MA&quot;,
  &quot;vessel_name&quot;: null,
  &quot;subscription_tier&quot;: null,
  &quot;stripe_customer_id&quot;: &quot;cus_B9NoFAwamZzZok&quot;,
  &quot;subscription_id&quot;: null,
  &quot;is_active&quot;: false,
  &quot;payment_source&quot;: null,
  &quot;deleted_at&quot;: null
}</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 17, 2017 00:44:28 +0530</td></tr><tr><th>Params</th><td>#&lt;User id: 2, email: &quot;marlo@schoen.biz&quot;, created_at: &quot;2017-08-04 09:07:51&quot;, updated_at: &quot;2017-08-16 19:01:56&quot;, first_name: &quot;First_Name&quot;, last_name: nil, home_port: nil, state_waters: &quot;MA&quot;, vessel_name: nil, subscription_tier: nil, stripe_customer_id: &quot;cus_B9NoFAwamZzZok&quot;, subscription_id: nil, is_active: false, payment_source: nil, deleted_at: nil&gt;</td></tr></table>
