### ISSUE TITLE
# (NoMethodError) "undefined method `each' for nil:NilClass"

### ISSUE THREAD

**Issue by tannakartikey** [tannakartikey/currents#44]
<table><tr><th>Exception</th><td>undefined method `each&#39; for nil:NilClass</td></tr><tr><th>Last Occurrence</th><td>September 02, 2017 16:03:21 +0530</td></tr><tr><th>Count</th><td>9</td></tr></table>

## Stack Trace
<pre><a href='https://github.com/tannakartikey/currents/blob/f473102edffc6f494cdb3650ddbaabc4478b5eee/app/models/stripe_customer.rb#L23'>[app].../app/models/stripe_customer.rb:23:in `delete_all_sources'</a>
<a href='https://github.com/tannakartikey/currents/blob/f473102edffc6f494cdb3650ddbaabc4478b5eee/app/models/exception_wrapper.rb#L11'>[app].../app/models/exception_wrapper.rb:11:in `call'</a>
<a href='https://github.com/tannakartikey/currents/blob/f473102edffc6f494cdb3650ddbaabc4478b5eee/app/models/exception_wrapper.rb#L11'>[app].../app/models/exception_wrapper.rb:11:in `block (2 levels) in singleton class'</a>
<a href='https://github.com/tannakartikey/currents/blob/f473102edffc6f494cdb3650ddbaabc4478b5eee/app/controllers/stripe_controller.rb#L42'>[app].../app/controllers/stripe_controller.rb:42:in `event_process'</a>
<a href='https://github.com/tannakartikey/currents/blob/f473102edffc6f494cdb3650ddbaabc4478b5eee/app/controllers/stripe_controller.rb#L19'>[app].../app/controllers/stripe_controller.rb:19:in `block in events'</a></pre>
Fingerprint: `287f3aae96a75bb969440410bed667d489147002`

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 17, 2017 11:25:25 +0530</td></tr><tr><th>Params</th><td>&quot;cus_BE8nQ7vU40uiZA&quot;</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 17, 2017 11:29:29 +0530</td></tr><tr><th>Params</th><td>&quot;cus_B9NoFAwamZzZok&quot;</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 17, 2017 14:35:12 +0530</td></tr><tr><th>Params</th><td>&quot;cus_BEBGv7VsGBtrIf&quot;</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 17, 2017 14:53:02 +0530</td></tr><tr><th>Params</th><td>&quot;cus_BECU0k3QBTY20F&quot;</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 17, 2017 15:37:07 +0530</td></tr><tr><th>Params</th><td>&quot;cus_BEBCXKRfhJQDxv&quot;</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 30, 2017 19:50:57 +0530</td></tr><tr><th>Params</th><td>&quot;cus_BJ1cLzc7y1qKmK&quot;</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 30, 2017 20:51:39 +0530</td></tr><tr><th>Params</th><td>&quot;cus_BJ9GJc8ra3KFRT&quot;</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 31, 2017 16:55:00 +0530</td></tr><tr><th>Params</th><td>&quot;cus_BJ1cLzc7y1qKmK&quot;</td></tr></table>

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>September 02, 2017 16:03:21 +0530</td></tr><tr><th>Params</th><td>&quot;cus_BJ1cLzc7y1qKmK&quot;</td></tr></table>
