### ISSUE TITLE
# (NoMethodError) "undefined method `stripe_customer_id' for "cus_BEBCXKRfhJQDxv":String
Did you mean?  strip_heredoc"

### ISSUE THREAD

**Issue by tannakartikey** [tannakartikey/currents#48]
<table><tr><th>Exception</th><td>undefined method `stripe_customer_id&#39; for &quot;cus_BEBCXKRfhJQDxv&quot;:String
Did you mean?  strip_heredoc</td></tr><tr><th>Last Occurrence</th><td>August 17, 2017 15:37:03 +0530</td></tr><tr><th>Count</th><td>1</td></tr></table>

## Stack Trace
<pre><a href='https://github.com/tannakartikey/currents/blob/f473102edffc6f494cdb3650ddbaabc4478b5eee/app/models/stripe_customer.rb#L10'>[app].../app/models/stripe_customer.rb:10:in `retrieve'</a>
<a href='https://github.com/tannakartikey/currents/blob/f473102edffc6f494cdb3650ddbaabc4478b5eee/app/models/exception_wrapper.rb#L11'>[app].../app/models/exception_wrapper.rb:11:in `call'</a>
<a href='https://github.com/tannakartikey/currents/blob/f473102edffc6f494cdb3650ddbaabc4478b5eee/app/models/exception_wrapper.rb#L11'>[app].../app/models/exception_wrapper.rb:11:in `block (2 levels) in singleton class'</a>
<a href='https://github.com/tannakartikey/currents/blob/f473102edffc6f494cdb3650ddbaabc4478b5eee/app/models/stripe_customer.rb#L22'>[app].../app/models/stripe_customer.rb:22:in `delete_all_sources'</a>
<a href='https://github.com/tannakartikey/currents/blob/f473102edffc6f494cdb3650ddbaabc4478b5eee/app/models/exception_wrapper.rb#L11'>[app].../app/models/exception_wrapper.rb:11:in `call'</a>
<a href='https://github.com/tannakartikey/currents/blob/f473102edffc6f494cdb3650ddbaabc4478b5eee/app/models/exception_wrapper.rb#L11'>[app].../app/models/exception_wrapper.rb:11:in `block (2 levels) in singleton class'</a>
<a href='https://github.com/tannakartikey/currents/blob/f473102edffc6f494cdb3650ddbaabc4478b5eee/app/controllers/stripe_controller.rb#L42'>[app].../app/controllers/stripe_controller.rb:42:in `event_process'</a>
<a href='https://github.com/tannakartikey/currents/blob/f473102edffc6f494cdb3650ddbaabc4478b5eee/app/controllers/stripe_controller.rb#L19'>[app].../app/controllers/stripe_controller.rb:19:in `block in events'</a></pre>
Fingerprint: `3d32246e9e074b227bf3269d1e454be3408af7b5`

**Comment by tannakartikey** [comment]
<table><tr><th>Occurred At</th><td>August 17, 2017 15:37:03 +0530</td></tr><tr><th>Params</th><td>&quot;cus_BEBCXKRfhJQDxv&quot;</td></tr></table>
